### ISSUE TITLE
Grid view keeps turning off - not working unless I leave and come back to call

### ISSUE THREAD

**Issue by j9w** [Fugiman/google-meet-grid-view#100]
Hello, 

I have installed the grid extension. Yet it only shows me the grid view when I join the session, and nobody after that. 

So  if I join when there are 10 people on the call, I can see them all. however if an 11th joins I can’t see them. So in effect I can’t see anybody who joins after me on the grid.

When I check the settings, I can see that it’s turned off the grid, and even if I click it back on it doesn’t adapt my current view  (so can still only see those who joined before me). If I leave the call and re-join, I can see everybody on the call in grid view , but again not those who join after me.

It seems that it’s turning off all the time and not allowing me to turn it back on or  adapt my view when in the session.

Have uninstalled and re-installed, turned Mac on and off.

**Software used:**
 - OS [e.g. Windows 10]: Mac OS Catalina Version 10.15.4
 - Browser [e.g. Chrome, Firefox]: Chrime
 - Version [e.g. 22]: Version 81.0.4044.122 (Official Build) (64-bit)
 - Extension [e.g. Official Chrome Extension, Tampermonkey]: Official Chrome extension
 - Grid View Version [e.g. 1.19, 1.23]:  1.28.0

**Additional context**

**Comment by Fugiman** [comment]
Unfortunately I'm not able to replicate this. On Mac OS Mojave (10.14) with Chrome 81 and the chrome extension v1.28.0 I was able to join a Meet with 10 people, enable grid view and then see the 11th, 12th, etc person who joined after me as they joined. I'm also confused as it should never disable the grid without you clicking either the checkbox in the extension menu or the grid button in the top-right of the meet.

Are you able to share any screenshots (optionally with other participants redacted) of what you're seeing? Do you have any other extensions running on the page?

**Comment by j9w** [comment]
Thanks - I’m using it again tomorrow - so if the issue continues I’ll screen shot and post.
Janine

On 1 May 2020, at 10:37, Fugi <notifications@github.com> wrote:


Unfortunately I'm not able to replicate this. On Mac OS Mojave (10.14) with Chrome 81 and the chrome extension v1.28.0 I was able to join a Meet with 10 people, enable grid view and then see the 11th, 12th, etc person who joined after me as they joined. I'm also confused as it should never disable the grid without you clicking either the checkbox in the extension menu or the grid button in the top-right of the meet.

Are you able to share any screenshots (optionally with other participants redacted) of what you're seeing? Do you have any other extensions running on the page?

**Comment by h2o834life** [comment]
I am having the same problem...I can see that a new person has entered but I cannot see them in the grid...if i leave and re enter then they appear in the gird. I am a teacher and I cannot leave my students to fix the problem!

**Comment by Gass-by-Revi** [comment]
Yo no estoy teniendo ese problema, yo puedo y de hecho estoy viendo a más de 30 personas, y sin problema alguno, además puedo quitar del Grid View a quien no me apetezca ver. Por tanto tal vez el error no sea del programa sino de su dispositivo

**Comment by Gass-by-Revi** [comment]
> Estoy teniendo el mismo problema ... Puedo ver que ha entrado una nueva persona pero no puedo verla en la cuadrícula ... si me voy y vuelvo a entrar, aparecen en el ceñidor. ¡Soy maestra y no puedo dejar a mis alumnos para solucionar el problema!

pruebe a quitar el Grid View y volver a conectarlo. Si sigue sin funcionar cambie la vista de los participantes a modo mosaico. a mi por lo menos en un primer momento me dio error y tras hacer esto no me ha vuelto a pasar. Espero que le sirva de ayuda

**Comment by Gass-by-Revi** [comment]
> Hola,
> 
> He instalado la extensión de la cuadrícula. Sin embargo, solo me muestra la vista de cuadrícula cuando me uno a la sesión, y nadie después de eso.
> 
> Entonces, si me uno cuando hay 10 personas en la llamada, puedo verlos a todos. Sin embargo, si un 11 se une, no puedo verlos. En efecto, no puedo ver a nadie que se una a mí en la parrilla.
> 
> Cuando verifico la configuración, puedo ver que está apagada de la cuadrícula, e incluso si vuelvo a hacer clic en ella, no adapta mi vista actual (por lo tanto, solo puedo ver a aquellos que se unieron antes que yo). Si dejo la llamada y me vuelvo a unir, puedo ver a todos en la llamada en la vista de cuadrícula, pero nuevamente no a los que se unen después de mí.
> 
> Parece que se apaga todo el tiempo y no me permite volver a encenderlo o adaptar mi vista cuando estoy en la sesión.
> 
> He desinstalado y reinstalado, encendido y apagado de Mac.
> 
> **Software utilizado:**
> 
> * SO [por ejemplo, Windows 10]: Mac OS Catalina Versión 10.15.4
> * Navegador [por ejemplo, Chrome, Firefox]: Chrime
> * Versión [por ejemplo, 22]: Versión 81.0.4044.122 (Versión oficial) (64 bits)
> * Extensión [por ejemplo, extensión oficial de Chrome, Tampermonkey]: extensión oficial de Chrome
> * Versión de vista de cuadrícula [por ejemplo, 1.19, 1.23]: 1.28.0
> 
> **Contexto adicional**

pues a mi no me ocurre eso, pero pruebe a cambiar al modo mosaico, y si no, donde el grid view, puede seleccionar varias opciones. a pesar de todo ahora intentaré publicar capturas de pantalla indicando a que me refiero.

**Comment by Gass-by-Revi** [comment]
![Screenshot 2020-05-04 at 12 02 19](https://user-images.githubusercontent.com/64775775/80955281-50ccd700-8dff-11ea-8249-5c8a02d2e4cd.png)
![Screenshot 2020-05-04 at 12 01 22](https://user-images.githubusercontent.com/64775775/80955287-52969a80-8dff-11ea-9eeb-5229c487448b.png)

**Comment by Gass-by-Revi** [comment]
a mi me sale en español pues estoy en España, pero más o menos tendréis una referencia

**Comment by Gass-by-Revi** [comment]
¿a ustedes les aparece a las personas en el grid en fila? ¿o les aparece en vista de cuadrícula?
![Screenshot 2020-05-25 at 12 07 25](https://user-images.githubusercontent.com/64775775/82805243-f5cd5380-9e83-11ea-99cc-620171a09900.png)

**Comment by Fugiman** [comment]
Please see #133
