### ISSUE TITLE
Pinning the bottom bar

### ISSUE THREAD

**Issue by jmcnamee-sfdc** [Fugiman/google-meet-grid-view#102]
**Is your feature request related to a problem? Please describe.**
The bottom bar keeps appearing/disappearing when you move mouse - frustrating if you need to use this menu quickly

**Describe the solution you'd like**
an checkbox to force it to stay visible

**Describe alternatives you've considered**
I've considered writing a greasemonkey script, but it might as well all be in one extension

**Additional context**
just the bar at the bottom with the mute,hang-up and camera toggle buttons

**Comment by jmcnamee-sfdc** [comment]
better still, if the bar's contents was moved to the top, there'd be no need to hide it ever as there is empty space already there

**Comment by Fugiman** [comment]
Forcing the bottom bar to stay open reduces the amount of space for videos, adding a toggle clutters the menu further, and moving it to the top would conflict with the other elements at the top of the page. There's no solution that I'm thrilled with, but I'll continue to think about it.

In the mean time you can use CTRL+D to toggle the mute button. Other useful keyboard shortcuts are explained at https://support.google.com/meet/answer/9298571?hl=en

**Comment by jmcnamee-sfdc** [comment]
The issue is that when you're full screen and you are working with multiple monitors and try for example to take a snip of a presentation on screen - as soon as you focus the window the menu appears, the videos all resize to smaller space - this is the behaviour I'm most interested in fixing. Personally I think there's lots of dead space at the top in the centre of the screen, especially if you reduce the size of the icons :)

**Comment by Fugiman** [comment]
If you're looking to take a snip of the meeting you can enable screen capture mode temporarily which ensure the videos won't resize on hover. This also seems to be a very different use case then what was originally laid out.

While there's a lot of dead space at the top on a large monitor, many users have much lower resolutions. The top bar has to fit the "___ is currently presenting text" in addition to the top-right menu of participants, chat and video preview. The bottom bar also has a lot of information to move; in addition to mute/hang-up/camera buttons it has the meeting details, captions, presentation menu, and the additional options menu. Moving all that and ensuring it fits and continues to work on small monitors isn't trivial.

**Comment by jmcnamee-sfdc** [comment]
The two issues are part of the same issue - the UI changes when I move my mouse and I find the resizing annoying as best described in #116 

I get your point about not moving the bar to the top - maybe just the option to fix at the bottom to both keep it visible and prevent resizing would be ideal.

re screen capture mode - this works to an extent but it forces the aspect ratio etc - fixing the issue above would allow screen shotting 'natively'

**Comment by armordog** [comment]
Fwiw: I'd like to be able to pin the bottom bar so I can easily see/change my mute status.

(Wonderful script. Much appreciated =])

**Comment by jmcnamee-sfdc** [comment]
@Fugiman  - Comment by @armordog is probably the best description. It was my original reason for this feature request :)

**Comment by Fugiman** [comment]
This has been added to the Advanced Settings menu in v1.30
