### ISSUE TITLE
Add the 'Hide Participant' button to the participant menu

### ISSUE THREAD

**Issue by iampegram** [Fugiman/google-meet-grid-view#105]
**Is your feature request related to a problem? Please describe.**
I'm using this plugin in conjunction with my plugin that hides the mouse-over widget on videos to keep the screen capture output clean. I see that you added a 'hide participant' button to the mouse-over widget, but this is not accessible with the other plugin.

**Describe the solution you'd like**
If you could duplicate that button in the Participant side bar, in the little sub-menu that contains the same pin/mute/boot buttons, that would be awesome.

**Additional context**
My plugin is a CSS hack I made that injects "div.P48BS {display:none;}" into the site's CSS, you're free to add that to your plugin as an option, if you'd like.

**Comment by Fugiman** [comment]
The hide participant button should already exist in the participant menu as of v1.28.
<img width="163" alt="hide participant" src="https://user-images.githubusercontent.com/545785/81128805-121a4800-8ef7-11ea-8599-b4594ef54a8f.png">

If you're on v1.28 and aren't seeing it please share as much information as you can, including:
OS [e.g. Windows 10]:
Browser [e.g. Chrome, Firefox]:
Version [e.g. 22]:
Extension [e.g. Official Chrome Extension, Tampermonkey]:
Grid View Version [e.g. 1.19, 1.23]:

**Comment by iampegram** [comment]
My bad, I forgot to refresh after installing the update. It's there. Keep up the good work!
