### ISSUE TITLE
Automatically pin partecipant who's speaking

### ISSUE THREAD

**Issue by AlbertoCentonze** [Fugiman/google-meet-grid-view#106]
While the grid is enabled it would be really cool to make the participant who's speaking dynamically get bigger as if it was pinned. Obviously you should always be able to pin someone anyway. It would make the grid even more useful

**Comment by Fugiman** [comment]
Considering how many people have asked for features to move participants _less_, I will never be implementing this. If you would like the speaker to be emphasized I encourage you to use a different layout such as the native "spotlight" layout.
