### ISSUE TITLE
flip my own video

### ISSUE THREAD

**Issue by scottcrevier** [Fugiman/google-meet-grid-view#111]
**Is your feature request related to a problem? Please describe.**
All videos in the grid appear as they should, except my own is flipped horizontally.

**Describe the solution you'd like**
Offer an option to flip my own video, so that I see it the way everyone else sees it. Perhaps a simple checkbox similar to other options.

**Describe alternatives you've considered**
No other alternatives considered.

**Additional context**
I believe the video is flipped by default to perhaps make it easier for users to have a better perspective as they see themselves move, turn their head, point, etc., like looking at yourself in the mirror. I understand this need. I'd also like to have the option to flip it so that it's like all others, and it's easier to see my video as it appears to others, especially to properly read words that are in the frame (i.e. on a sign on the wall).

**Comment by Fugiman** [comment]
This has been added to the Advanced Settings menu in v1.30
