### ISSUE TITLE
Prevent names and mic status from auto-hiding

### ISSUE THREAD

**Issue by henrik242** [Fugiman/google-meet-grid-view#114]
It would be cool if we could prevent both the bottom menu bar, and the individual names/mic status from hiding.

**Comment by Fugiman** [comment]
When do individual names/mic status hide? I haven't seen that behavior.

bottom menu bar hiding is being tracked in #102

**Comment by henrik242** [comment]
They hide all the time for me. Seem to be after some seconds, usually at the same time the bottom bar disappears

**Comment by gabriel-r** [comment]
I think you mean the Meet toolbar. I also have a problem with that, but it's mostly because it's pushing and resizing the grid when it does. See my related issue #116 116

**Comment by henrik242** [comment]
> think you mean the Meet toolbar.

Nope, I mean the mic and name overlay that is on every participant's video

**Comment by Fugiman** [comment]
As far as I can tell, Google Meet does not hide the mic & name overlay, and my extension doesn't either. Can you please make sure you don't have a different extension that is doing this? Alternatively you may be in a testing group for Google Meet and I won't be able to help until I'm also given access to that feature.

**Comment by henrik242** [comment]
I'm not able to replicate it now, so I might have been victim of an A/B test or something.  Thanks for looking into it though!  I'll close this now, and reopen if it happens again.

**Comment by henrik242** [comment]
It happens for me again.  I'm in Firefox Developer Edition using av business account.  Here are before/after images: <img width="106" alt="Skjermbilde 2020-05-18 kl  10 51 58" src="https://user-images.githubusercontent.com/129931/82195435-9659cb80-98f8-11ea-823b-8d2df491210e.png">
<img width="127" alt="Skjermbilde 2020-05-18 kl  10 51 06" src="https://user-images.githubusercontent.com/129931/82195442-9954bc00-98f8-11ea-872e-014c2c48c4ef.png">

**Comment by sreyemnayr** [comment]
I think that Google's new native grid layout hides the names/icons except for the person speaking (the highlight is also only underneath the person's camera rather than a full border). Make sure you actually have Grid View enabled.

**Comment by henrik242** [comment]
@sreyemnayr Yup, you're right. "Auto" is the default layout, and it now chooses "Tiled" as the default.  "Tiled" will auto-hide the mic/name.  If I choose "Sidebar" manually, the mic/name doesn't auto-hide.

So the default will be to auto-hide mic/name.  A workaround would be for google-meet-grid-view to select "Sidebar" by default?

**Comment by Eagle-Man** [comment]
@henrik242 I think that means you don't have Grid View actually enabled.  I haven't had this problem and I use it all day every day for teaching.  The Grid View Extension layout should override any Google Meet layout, so if the Meet layouts are changing and affecting you, then Grid View is off.

**Comment by henrik242** [comment]
> I think that means you don't have Grid View actually enabled. 

Nope, it's enabled

**Comment by Fugiman** [comment]
Finally figured out that this happens when videos get too small. A fix is in v1.33.

**Comment by henrik242** [comment]
Fantastic, thanks!
