### ISSUE TITLE
Non riesco a presentare da Meet

### ISSUE THREAD

**Issue by anninak89** [Fugiman/google-meet-grid-view#115]
Buongiorno,
entrando con Meet mi dice "Non stai presentando". Credo che sia il mio sistema AVG a bloccare la presentazione ma non so come modificare le impostazioni.
Potete aiutarmi?

Vi ringrazio.
Cordialmente
anninak89

**Comment by Fugiman** [comment]
This sounds like a problem with the native Meet functionality and I can not help you with it.
