### ISSUE TITLE
Meet toolbar should float on top of the grid instead of pushing/resizing it

### ISSUE THREAD

**Issue by gabriel-r** [Fugiman/google-meet-grid-view#116]
When the user is not interacting with the page, the toolbar is hidden, which is nice. 
When the toolbar is hidden or shown, the grid is also resized to make room for it, which is annoying.

The toolbar appear or disappear _on top_ of the grid, not push it up, like it does in the regular Meet UI.

PS: I believe it's the annoying resizing that creates the other problems like #102

**Comment by Fugiman** [comment]
This functionality was added to support meetings with many participants as described in #80. Without resizing it would be impossible to pin/mute/hide/remove users on the bottom row once their videos got small enough to be obscured by the toolbar.

**Comment by Fugiman** [comment]
This has been added to the Advanced Settings menu in v1.30
