### ISSUE TITLE
Pinning one participant to the screen followed by another causes the 2nd pinned participant remain at the same original size

### ISSUE THREAD

**Issue by rodawg** [Fugiman/google-meet-grid-view#120]
**Describe what is broken**
Pinning one participant to the screen followed by pinning another, without unpinning the first participant, causes the second pinned participant remain at the same original size instead of resizing the second participant to replace the first participant.

**Expected behavior**
I would expect the second participant to be pinned to be enlarged and fully fit into the pinned frame instead of the just taking part of the frame size (with the rest being black). 

**Software used:**
 - OS [e.g. Windows 10]: Ubuntu Linux 18.04
 - Browser [e.g. Chrome, Firefox]: Chrome
 - Version [e.g. 22]: 81.0.4044.129 (Official Build) (64-bit)
 - Extension [e.g. Official Chrome Extension, Tampermonkey]: Official Chrome Extension
 - Grid View Version [e.g. 1.19, 1.23]: v1.30.0

**Comment by Eagle-Man** [comment]
I've experienced this as well.  Most of the time, for me, the video will eventually snap to fill the whole frame, but it does happen
(W7, W10, Chrome)

**Comment by Eagle-Man** [comment]
Update: I was just trying this.  For me, the second pinned video remains its small size until another object on the screen I guess forces an update of some kind, like the chat/people pane sliding out or the bottom menu bar disappearing.

OS: Windows 7
Browser: Chrome
Version: Version 81.0.4044.138 (Official Build) (64-bit)
Extension: Official Chrome Extension
Grid View Version: v1.30.0

**Comment by Fugiman** [comment]
Fixed in v1.31, thank you for the report!
