### ISSUE TITLE
Add advanced setting to always show the Bottom Toolbar

### ISSUE THREAD

**Issue by joelkesler** [Fugiman/google-meet-grid-view#121]
**Is your feature request related to a problem? Please describe.**
When using Google Meet in large groups, I want to keep my microphone muted I have something to say. 
Google Meet autohides the bottom toolbar, so I have to constantly wiggle my mouse to see if my microphone is still muted or unmuted

**Describe the solution you'd like**
I would like a way to always show the Bottom toolbar

**Describe alternatives you've considered**
An option in the Advanced Settings window to always show the Bottom Toolbar.

Bonus: Add way to style toolbar to be dark/black to blend in more with rest of interface

**Comment by Fugiman** [comment]
It already exists. Advanced Settings > Bottom Toolbar Behavior > Always show toolbar and resize grid

**Comment by joelkesler** [comment]
Oh man, sorry I missed that! Thanks!
