### ISSUE TITLE
Grid View Not Working

### ISSUE THREAD

**Issue by TDMcGovern** [Fugiman/google-meet-grid-view#123]
The grid view stopped working yesterday.  I have removed and reinstalled the extension, but I am not getting it to work properly.  I have made no changes to my computer between the last time this did work and now, so I don't believe there is any conflict.

![image](https://user-images.githubusercontent.com/65663279/82448976-7e10ba80-9a78-11ea-85c0-314bf39c9ab0.png)

**Comment by sreyemnayr** [comment]
It looks like from your extension bar that you have both the original stgnola version and the new official version installed. You'll want to uninstall the one with the 2020.05.xx version number.

**Comment by TDMcGovern** [comment]
Thanks, I'll test that out tomorrow.

*Timothy McGovern*

*Physics, Chemistry, and Forensics Teacher*

*Science Department Liaison*
*Dunellen High School*

Website
<https://sites.google.com/dunellenschools.org/mcgoverns-website/home>
