### ISSUE TITLE
"Grid" showing as a list

### ISSUE THREAD

**Issue by Katedam** [Fugiman/google-meet-grid-view#126]
**Describe what is broken**
This was working just fine this morning and then I joined a meeting after lunch and now the grid is more like a list with everyone's picture centered in the middle of each list item.

**Expected behavior**
I expected a grid ;-)

**Screenshots**
![image](https://user-images.githubusercontent.com/35700876/82708587-777a7280-9c33-11ea-8ed0-9e019ed1cbe1.png)

**Software used:**
 - OS [e.g. Windows 10]: macOS 10.15.3
 - Browser [e.g. Chrome, Firefox]: chrome
 - Version [e.g. 22]: Version 81.0.4044.129 
 - Extension [e.g. Official Chrome Extension, Tampermonkey]: Official Chrome
 - Grid View Version [e.g. 1.19, 1.23]: 2020.4.30

**Comment by jgelston** [comment]
Same! Stopped working just after 1;30 PST. Chrome OS Version 81.0.4044.141 (Official Build) (64-bit)

**Comment by markomili** [comment]
Same here. Looks like Google's changes broke the extension.

**Comment by tifilib** [comment]
Me too!  I was having a story time this afternoon and all of a sudden it switched and stopped working on me.  I've been trying since then to figure out what I have done wrong!!!

**Comment by Katedam** [comment]
I haven't updated Chrome yet so I don't think that's the cause per say...

**Comment by Yukeechan** [comment]
I was having the same problem. Now only a few pictures lined up in vertical.

**Comment by pablogirado** [comment]
The same mistake. Also, I can't see all the users. Google Chrome Versión 83.0.4103.61 (Build oficial) (64 bits)

**Comment by jctovilla** [comment]
The same mistake, apparently something changed in the Meet that affected GridView

**Comment by Fugiman** [comment]
Yep, google changed some of the code that this extension relies on. I've been working on a fix for the past several hours and should have a fix out later tonight.

**Comment by brianchandotcom** [comment]
@Fugiman you're awesome! Thank you! My church youth group relies on this and Bible study is just not the same without it.

**Comment by nizaaa** [comment]
@Fugiman I really appreciate your effort. I am praying it is fixed as soon as possible since my invigilators are using grid view to monitor online exam tomorrow. Thank you.

**Comment by Fugiman** [comment]
v1.31 is done and currently going through review. It fixes Grid View to work with the new Google Meet code and fixes a few other bugs. It also should make pinned videos & presentations work better when the window is only half the screen.

I'll close this issue when v1.31 is through review and fully available.

**Comment by maxbambi** [comment]
@Fugiman , very quick fix!

**Comment by Fugiman** [comment]
Firefox and Chrome have been updated to 1.31 and should be working, so I'm going to close this issue. The Edge extension is *not* updated yet, but their approvals tend to take several days, sorry.

Please ensure you're updated to v1.31 and if you still have any problems please open a new ticket. Thanks to everyone for the prompt reports and apologies for the 15 hours of downtime.

**Comment by sreyemnayr** [comment]
Reminder that the stgnola extension will not receive this update, so everyone should switch to Chris' extension. Thanks for the quick work bringing back functionality, @Fugiman !

**Comment by Katedam** [comment]
@Fugiman Thanks!
