### ISSUE TITLE
Grid is broken

### ISSUE THREAD

**Issue by JeremySpecright** [Fugiman/google-meet-grid-view#127]
Grid is not working at all so much that even when disabled I can't even see normal Google Hangouts

**Software used:**
 - OS [e.g. Windows 10]:
 - Browser [e.g. Chrome, Firefox]:
 - Version [e.g. 22]:
 - Extension [e.g. Official Chrome Extension, Tampermonkey]:
 - Grid View Version [e.g. 1.19, 1.23]: 

**Additional context**

**Comment by igtm** [comment]
same here

**Comment by Fugiman** [comment]
duplicate of #126
