### ISSUE TITLE
Grid View is Broken

### ISSUE THREAD

**Issue by Rickey8256** [Fugiman/google-meet-grid-view#128]
**Software used:**
 - OS [e.g. Windows 10]:
 - Browser [e.g. Chrome]:
 - Version [e.g. 22]:
 - Extension [e.g. Official Chrome Extension, Tampermonkey]:
 - Grid View Version [e.g. 1.19, 1.23]:

**Comment by Fugiman** [comment]
duplicate of #126

**Comment by Euzeni** [comment]
Bom dia!
O meet permite que eu possa numa reunião encaminhar grupos para salas
separadas e depois trazê-las de volta? Como se estivessemos numa plenária
maior, fossemos fazer atividades em grupos menores e depois retornar?

Em sáb., 23 de mai. de 2020 às 01:07, Fugi <notifications@github.com>
escreveu:
