### ISSUE TITLE
Feature Request: Push to Talk

### ISSUE THREAD

**Issue by amadotejada** [Fugiman/google-meet-grid-view#13]
The highlighting speaker feature is awesome! Now that we can easily see who is speaking in a large meeting I was wondering if it makes sense to add a check box to enable something like "Push to talk"

Something like this:
https://gist.github.com/benjaminoakes/455942d154145876b60e920485b9d23a#file-google-meet-spacebar-user-js

Totally unrelated but I though it would be good to put on your radar. Cheers

Thanks again

**Comment by Fugiman** [comment]
Heya, glad you're enjoying it! I'm trying to ensure this script stays focused on offering a functional grid layout and nothing more. This ensures I'm able to maintain it and that it's clear what users are installing. While the push to talk script is interesting, I'd be very uncomfortable adding a global keypress listener in that fashion as it could confuse users who aren't expecting it, and it could be hard to educate users as to how it works. I'd encourage you to keep using the existing script for that purpose.

**Comment by amadotejada** [comment]
Awesome. Thanks for the insight!

**Comment by Fugiman** [comment]
I've just found out that CTRL+D toggles the mute button, so I recommend trying that out!

**Comment by amadotejada** [comment]
😎 totally that's I personally use
