### ISSUE TITLE
la grid di meet

### ISSUE THREAD

**Issue by raguconfezionato** [Fugiman/google-meet-grid-view#134]
fino a ieri funzionava bene, oggi tutto bloccato.
non so nulla di programmazione, help me

**Comment by Xinne** [comment]
Duplicate of #133

**Comment by Fylls** [comment]
translation: 

>" It was working until yesterday. strangely today it is all broken.
>  I don't know anything about coding please help me out"

**Comment by Fugiman** [comment]
As Xinne said, this is a duplicate of #133
