### ISSUE TITLE
grid view broken both from button and from layout settings

### ISSUE THREAD

**Issue by Fylls** [Fugiman/google-meet-grid-view#136]
**Describe what is broken**
A clear and concise description of what isn't working.

the grid itself

**Expected behavior**

to view all participants in a grid, not a column

**Screenshots**

![yy](https://user-images.githubusercontent.com/55017307/82789126-125c9200-9e6a-11ea-8cc2-e9f509458574.png)

**Comment by Xinne** [comment]
Duplicate of #133

**Comment by Fylls** [comment]
"column view" would be a fitting name

**Comment by Fugiman** [comment]
As Xinne said, this is a duplicate of #133

**Comment by Gass-by-Revi** [comment]
> **Describa lo que está roto.**
> Una descripción clara y concisa de lo que no funciona.
> 
> la grilla misma
> 
> **Comportamiento esperado**
> Una descripción clara y concisa de lo que esperaba que sucediera.
> 
> para ver a todos los participantes en una cuadrícula, no en una columna
> 
> **Capturas de pantalla**
> Si corresponde, agregue capturas de pantalla para ayudar a explicar su problema.
> 
> ![yy](https://user-images.githubusercontent.com/55017307/82789126-125c9200-9e6a-11ea-8cc2-e9f509458574.png)

me ocurre lo mismo
