### ISSUE TITLE
Gridview isn't working anymore

### ISSUE THREAD

**Issue by ajgankema** [Fugiman/google-meet-grid-view#137]
**Describe what is broken**
The Grid View is only show a column with participants. 
And you don't see yourself anymore.

**Software used:**
 - OS Windows 10
 - Browser Chrome
 - Version: 83.0.4103.61
 - Extension : Gridview
 - Grid View Version [e.g. 1.19, 1.23]: 2020.4.30

**Comment by Xinne** [comment]
Duplicate of #133

**Comment by milicontreras** [comment]
The same thing is happening to me

**Comment by Fugiman** [comment]
As Xinne said, this is a duplicate of #133
