### ISSUE TITLE
BUG Griglia | Grid View Bugged :(

### ISSUE THREAD

**Issue by AnonHexo** [Fugiman/google-meet-grid-view#143]
@Fugiman 
__the extension load normally, all fine but whenever i enter a google meet all the people are streched in horizontal lines and i can't even see all people.__
**fix pls**

__l'estensione si carica normalmente, tutto bene ma ogni volta che entro in una riunone per la scuola (purtroppo) vedo tutte le persone sono schiacciate in linee orizzontali e non riesco nemmeno a vedere tutte le persone; la animazione nella barra in ondo è completamente assente...__
**fixate plzz**

`if u need help i wold like to lean a bit of js and help!`

**Comment by AnonHexo** [comment]
OS: Windows 10 64bit
CPU: i5 G Series @ 1,0 GHz [boosted to 2,90GHz (no overclock)]
GPU: Intel UHD + NVIDIA Geforce Mx 230
RAM: 8GB
HHD: 512GB

**Comment by Gass-by-Revi** [comment]
> SO: Windows 10
> CPU de 64 bits : i5 G Series @ 1,0 GHz [aumentado a 2,90GHz (sin overclock)]
> GPU: Intel UHD + NVIDIA Geforce Mx 230
> RAM: 8GB
> HHD: 512GB
> 
> Navegador: Chrome
> Versión de Chrome: 81.0.4044.138
> Versión de JavaScript de Chrome: V8 8.1.307.32
> Versión de extensión: v2020.4.30
> **Extensión de Chrome Store**

¿Cual es la versión que tienes del Grid View?

**Comment by Fugiman** [comment]
>Extension Version: v2020.4.30

That's not my extension. Uninstall it and install https://chrome.google.com/webstore/detail/google-meet-grid-view/kklailfgofogmmdlhgmjgenehkjoioip instead
