### ISSUE TITLE
Today, after having Gridview work on a daily basis for my schoolwork, it isn't working. Now, whenever I try to use it during a Google Meet, it shows a long list, up-and-down, rather than in a grid, of some of the participants, not all of them. When I try to restart the program, by uninstalling and reinstalling it, it might work for that google meet, and stop working yet again when I open the next one.  I have a Windows Laptop and use Google Chrome.

### ISSUE THREAD

**Issue by MitchMan1** [Fugiman/google-meet-grid-view#145]
_Before opening an issue, please check the existing open issues to see if somebody has already reported it! If something is horribly wrong, like all videos showing up in a single column, chances are somebody already reported it. Please reply in that issue instead._

**Describe what is broken**
A clear and concise description of what isn't working.

**Expected behavior**

**Screenshots**

**Software used:**
 - OS [e.g. Windows 10]:
 - Browser [e.g. Chrome, Firefox]:
 - Version [e.g. 22]:
 - Extension [e.g. Official Chrome Extension, Tampermonkey]:
 - Grid View Version [e.g. 1.19, 1.23]:

**Additional context**

**Comment by Gass-by-Revi** [comment]
Mire en #140 y #133

**Comment by Gass-by-Revi** [comment]
y cierre este problema, se está resolviendo en #140 y en #133

**Comment by JosephIaquinto** [comment]
Heads up, the title is supposed to be a short description like "Grid view is appearing as a vertical list instead of a grid" and you can add the details in the body of the issue, which you did not fill out.

**Comment by Gass-by-Revi** [comment]
i repeat it. it is been resolved in #140 and #133

**Comment by Fugiman** [comment]
You have multiple grid view extensions installed. Please remove the duplicates by visiting chrome://extensions and clicking "Remove" on all grid view extensions, then reinstall the official version from https://chrome.google.com/webstore/detail/google-meet-grid-view/kklailfgofogmmdlhgmjgenehkjoioip

If you still have issues please reply to #140 with the details requested in https://github.com/Fugiman/google-meet-grid-view/issues/140#issuecomment-634197803
