### ISSUE TITLE
Grid View is not working

### ISSUE THREAD

**Issue by kscott0919** [Fugiman/google-meet-grid-view#148]
I cannot see my students in my Grid View. I tried removing and re-installing the extension and it still didn't work. I have the latest official version of Chris Gamble's and the extension is not managed by my district. I do not have a screenshot because I didn't know I would need one to report the issue.

**Comment by Fugiman** [comment]
Please ensure you do not have any other grid extensions installed at chrome://extensions

**Comment by kscott0919** [comment]
Thank you. That was the problem! It is working now.
