### ISSUE TITLE
Prior to today I could see all 30 of my students in the grid.   When I updated today, now I can only see 20.  I NEED to see all 30.  Is there a way to make this happen ASAP. Thanks 

### ISSUE THREAD

**Issue by skirker** [Fugiman/google-meet-grid-view#149]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Fugiman** [comment]
Please make sure you are using the extension from https://chrome.google.com/webstore/detail/google-meet-grid-view/kklailfgofogmmdlhgmjgenehkjoioip and that you have v1.32 installed. Also please check that you don't have any other extensions installed.

If you are using v1.32 and have ensured you have no other grid view extensions at chrome://extensions please
1) Share a screenshot of what you see
2) Press CTRL+SHIFT+J and share all lines starting with [google-meet-grid-view]

**Comment by skirker** [comment]
It says installed by my administrator.  I tried to connect the photo here.  Thanks 
![206B0865-B00F-41F0-A45A-8CCA0B3D4A8D](https://user-images.githubusercontent.com/65983276/82960643-e75c6600-9f6f-11ea-9b6c-eddb18ed65e6.jpeg)

**Comment by Fugiman** [comment]
Please make sure you do not have any other grid view extensions installed. Also please share a screenshot of you in a meeting illustrating the issue.

**Comment by Eagle-Man** [comment]
> It says installed by my administrator. I tried to connect the photo here. Thanks
Have you restarted your browser and/or computer since the update?  I know on Chromebooks, it may not pull the new version from the administrator right away, even though it says the update is installed, and the Chromebook needs to be powered off and then on.

**Comment by skirker** [comment]
That worked.  Thank you for your help.
