### ISSUE TITLE
Presentation in Grid View

### ISSUE THREAD

**Issue by ruruboxer** [Fugiman/google-meet-grid-view#151]
**Is your feature request related to a problem? Please describe.**
** I would appreciate my presentation showing up as a tile so I can see what the students see. **
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Fugiman** [comment]
Sure. Added in v1.33

**Comment by Fugiman** [comment]
In v1.34 this has been moved to an Advanced Setting that defaults to off, FYI.
