### ISSUE TITLE
Pictures are scattered

### ISSUE THREAD

**Issue by Devbbsr** [Fugiman/google-meet-grid-view#152]
_Before opening an issue, please check the existing open issues to see if somebody has already reported it! If something is horribly wrong, like all videos showing up in a single column, chances are somebody already reported it. Please reply in that issue instead._

**Describe what is broken**
A clear and concise description of what isn't working.

**Expected behavior**

**Screenshots**

**Software used:**
 - OS [e.g. Windows 10]:
 - Browser [e.g. Chrome, Firefox]:
 - Version [e.g. 22]:
 - Extension [e.g. Official Chrome Extension, Tampermonkey]:
 - Grid View Version [e.g. 1.19, 1.23]:

**Additional context**

**Comment by Fugiman** [comment]
"Pictures are scattered" is not descriptive enough. Please fill out the form and include a picture of what the issue is.
