### ISSUE TITLE
Error on Chrome Webstore

### ISSUE THREAD

**Issue by JeroenVinck** [Fugiman/google-meet-grid-view#153]
I can't install the extension in Chrome. Colleague's are having problems to.
It looks like Google is blocking the extension.
![Google Meet Grid View](https://user-images.githubusercontent.com/66004131/82994975-45865900-a003-11ea-8fa6-a24234facff8.jpg)
![GoogleMeetError404](https://user-images.githubusercontent.com/66004131/82995028-58992900-a003-11ea-9b54-24bd7f96dafe.png)

**Comment by santheman-nl** [comment]
Here it is: 
https://chrome.google.com/webstore/detail/google-meet-grid-view/kklailfgofogmmdlhgmjgenehkjoioip

**Comment by adamduff** [comment]
Yeah, we have the same problem - I managed to get it before it stopped working, but now we get a 404 on this page...

Chrome Extension: https://chrome.google.com/webstore/detail/kklailfgofogmmdlhgmjgenehkjoioip

(or "An error has occurred" if trying to get to it via the Chrome Web Store)

**Comment by santheman-nl** [comment]
It is back online

**Comment by adamduff** [comment]
Not yet for me...
![Capture](https://user-images.githubusercontent.com/29484392/82996207-8cbd1b80-9ffc-11ea-8884-7d6e770007b1.PNG)

**Comment by santheman-nl** [comment]
Strange, it must be a glitch since I have tried it on several devices with different internet connections. Half an hour ago it was offline, but now back online again.

**Comment by JeroenVinck** [comment]
Yeah! It's back online. Thank you.

**Comment by adamduff** [comment]
Yeah, it is strange - I can access the page from other browsers/devices, but not Chrome on Desktop PC (I have tried 2 different PC's, connecting over home Wifi and 4G - all the same with 404 on this page)

**Comment by JeroenVinck** [comment]
Teacher with Mac still having problems with Error404 in Chrome.

**Comment by Spankybe** [comment]
First clear browser cache (history, cookies, ...)
That worked for me!

**Comment by Fugiman** [comment]
I unfortunately do not have a solution other than "try clearing your cookies, refresh the page, and if it doesn't work come back later". This seems to be on Google's end :/

**Comment by adamduff** [comment]
Yeah, clearing Cookies worked for me (I didn't need to clear History) ;-)
Thanks!
