### ISSUE TITLE
la vista de cuadricula no funciona en esta pagina 

### ISSUE THREAD

**Issue by larasc** [Fugiman/google-meet-grid-view#154]
_Before opening an issue, please check the existing open issues to see if somebody has already reported it! If something is horribly wrong, like all videos showing up in a single column, chances are somebody [already](url) reported it. Please reply in that issue instead._

**Describe what is broken**
the grid view

**Expected behavior**
I expected to see all my classmates

**Screenshots**
![2020-05-27](https://user-images.githubusercontent.com/66012556/83013733-e1a86400-9ff3-11ea-8c0b-4fd073556f00.png)

**Software used:**
 - OS [e.g. Windows 10]:
 - Browser [e.g. Chrome, Firefox]:
 - Version [e.g. 22]:
 - Extension [e.g. Official Chrome Extension, Tampermonkey]:
 - Grid View Version [e.g. 1.19, 1.23]:

**Additional context**

**Comment by Gass-by-Revi** [comment]
> _Antes de abrir un problema, compruebe los problemas abiertos existentes para ver si alguien ya lo ha informado. Si algo está terriblemente mal, como todos los videos que aparecen en una sola columna, es probable que alguien [ya lo haya](url) informado. Por favor, responda en ese problema en su lugar._
> 
> **Describa lo que está roto en**
> la vista de cuadrícula.
> 
> **Comportamiento esperado**
> Esperaba ver a todos mis compañeros de clase
> 
> **Capturas de pantalla**
> ![2020-05-27](https://user-images.githubusercontent.com/66012556/83013733-e1a86400-9ff3-11ea-8c0b-4fd073556f00.png)
> 
> **Software utilizado:**
> 
> * SO [por ejemplo, Windows 10]:
> * Navegador [por ejemplo, Chrome, Firefox]:
> * Versión [por ejemplo, 22]:
> * Extensión [por ejemplo, extensión oficial de Chrome, Tampermonkey]:
> * Versión de vista de cuadrícula [por ejemplo, 1.19, 1.23]:
> 
> **Contexto adicional**
> Agregue cualquier otro contexto sobre el problema aquí.

one thing, for the next time, try to cover people's face. It's just a recommendation. I'm saying it only to respect the privacy of people and image rights
