### ISSUE TITLE
I can't see my students in grid view

### ISSUE THREAD

**Issue by StephanieMacD** [Fugiman/google-meet-grid-view#158]
_Before opening an issue, please check the existing open issues to see if somebody has already reported it! If something is horribly wrong, like all videos showing up in a single column, chances are somebody already reported it. Please reply in that issue instead._

**Describe what is broken**
A clear and concise description of what isn't working.

**Expected behavior**

**Screenshots**

**Software used:**
 - OS [e.g. Windows 10]:
 - Browser [e.g. Chrome, Firefox]:
 - Version [e.g. 22]:
 - Extension [e.g. Official Chrome Extension, Tampermonkey]:
 - Grid View Version [e.g. 1.19, 1.23]:

**Additional context**

**Comment by jacman23** [comment]
Describa lo que está roto.
I can't see my students in a grid.


Software utilizado:

MOJAVE 10.14.6
CHROME Versión 81.0.4044.138
Extensión: GOOGLE MEET GRID VIEW V. 1.33

![greet](https://user-images.githubusercontent.com/41385058/83042981-e2e38c00-a007-11ea-8c6d-bb976919b332.png)

**Comment by Eagle-Man** [comment]
@jacman23 Make sure you don't have any other Grid View extensions installed, as that is known to cause conflicts.

**Comment by jacman23** [comment]
No, tengo otras extensiones pero no son para vista de cuadrícula, son para hacer dibujos en la pantalla. Y antes me estaba funcionando bien, desde hace dos días comenzó el problema.

**Comment by mathteacherNY** [comment]
Same problem jacman23.  This has been working for weeks but now it no longer working.  There must've been a Chrome update that has broken the extension.

**Comment by Eagle-Man** [comment]
I don't think so.  My Chrome is up to date (Version 83.0.4103.61) and my Grid View 1.33 is working fine.
@mathteacherNY : what OS are you using? (I've seen other MacOS users still having issues)

**Comment by mathteacherNY** [comment]
I'm on Windows 10 using Chrome Version 81.0.4044.138 (Official Build) (64-bit)

My other machine is on Windows 7.  I'm also having problems on that as well as on Chrome OS on my Chromebook.

**Comment by Eagle-Man** [comment]
Very strange.  Works for me on Win7 and Win10, both up to date Chrome.
@mathteacherNY @jacman23 what other extensions do you have?  I wonder if it's a conflict with something else, as I'm not having issues on the same version, same Chrome, same OS.

**Comment by mathteacherNY** [comment]
Okay I restarted the computer again and went to extensions.  I saw 2 "Grid Views" appeared to be installed all of a sudden.  One had a 9 box grid and one was a 4 box grid.  I deleted both extensions and restarted the computer and reinstalled the Grid View extension and I'm thinking it appears to be working right now.

**Comment by mathteacherNY** [comment]
Well an uninstall and a restart and then a reinstall on my Chromebook is now working.  A few of my colleagues are having trouble as well.  Strange..

**Comment by mathteacherNY** [comment]
My wife's school district manages her profile and they had to push out an update to get it functioning again.  Nonetheless it is back to working!

**Comment by Gass-by-Revi** [comment]
> Describa lo que está roto.
> No puedo ver a mis alumnos en una cuadrícula.
> 
> Software utilizado:
> 
> MOJAVE 10.14.6
> CHROME Versión 81.0.4044.138
> Extensión: GOOGLE MEET GRID VIEW V. 1.33
> 
> ![saludar](https://user-images.githubusercontent.com/41385058/83042981-e2e38c00-a007-11ea-8c6d-bb976919b332.png)

@jacman23  Una sugerencia: para la próxima vez trate de ocultar la cara de los alumnos. Lo digo para que puedan preservar su intimidad, además de su seguridad. Se lo digo para el bien suyo y de sus estudiante,
