### ISSUE TITLE
Can you make new "show own presentation if show self view selected" optional?

### ISSUE THREAD

**Issue by sbressler** [Fugiman/google-meet-grid-view#161]
**Is your feature request related to a problem? Please describe.**
In 1.33 you defaulted to show one's presentation if self view is checked. I for one keep self-view checked but don't want this.

**Describe the solution you'd like**
Can you maybe default off, and then allow on in the Advanced Settings?

**Describe alternatives you've considered**
Default on and allow off in advanced settings?

**Additional context**
I don't have the background (I think all I can understand from is the commit history -- do you host discussion about this anywhere?) to understand why you added this default -- I'm sure some folks want it. But I for one don't, so would like to throw out my opinion that I'd love for it to be optional.

**Comment by Eagle-Man** [comment]
I'm not involved in this project, but I did see it as a feature request.  I think some teachers using this extension were having difficulty with not know what their students were seeing while presenting.

I do this manually, myself, by using my desktop for video and my laptop to present (write notes), that way I can manually create the view I want.  But I can see how this would be beneficial as an option and desired either way.

**Comment by Fugiman** [comment]
I can make this an advanced option, sure. It will be in v1.34

**Comment by sbressler** [comment]
Belatedly, THANK YOU!
