### ISSUE TITLE
I am no longer able to see everyone in our Google Meet. I added the Chris Gamble update and restarted my computer, but I get a message saying that the gridview is not running on this page. There is a link to get a source code available on Git Hub, but when I click on that link I don't know where the source code is. Please help! I cannot find the source code.

### ISSUE THREAD

**Issue by ctamashiro55** [Fugiman/google-meet-grid-view#164]
_Before opening an issue, please check the existing open issues to see if somebody has already reported it! If something is horribly wrong, like all videos showing up in a single column, chances are somebody already reported it. Please reply in that issue instead._

**Describe what is broken**
A clear and concise description of what isn't working.

**Expected behavior**

**Screenshots**

**Software used:**
 - OS [e.g. Windows 10]:
 - Browser [e.g. Chrome, Firefox]:
 - Version [e.g. 22]:
 - Extension [e.g. Official Chrome Extension, Tampermonkey]:
 - Grid View Version [e.g. 1.19, 1.23]:

**Additional context**

**Comment by Fugiman** [comment]
Grid view only "runs" when you are actually in a meeting. Please go to meet.google.com and join a meeting before trying to use it.
