### ISSUE TITLE
Grid view is still not working. Why? I have removed the extension, added it and again nothing. I am trying to teach and I like to see my class and I prefer meet over zoom BUT I will need to start using zoom if I don't have grid view. Please advise asap.

### ISSUE THREAD

**Issue by mangins** [Fugiman/google-meet-grid-view#165]
_Before opening an issue, please check the existing open issues to see if somebody has already reported it! If something is horribly wrong, like all videos showing up in a single column, chances are somebody already reported it. Please reply in that issue instead._

**Describe what is broken**
A clear and concise description of what isn't working.

**Expected behavior**

**Screenshots**

**Software used:**
 - OS [e.g. Windows 10]:
 - Browser [e.g. Chrome, Firefox]:
 - Version [e.g. 22]:
 - Extension [e.g. Official Chrome Extension, Tampermonkey]:
 - Grid View Version [e.g. 1.19, 1.23]:

**Additional context**

**Comment by Fugiman** [comment]
Ensure you've installed the official extension: https://chrome.google.com/webstore/detail/google-meet-grid-view/kklailfgofogmmdlhgmjgenehkjoioip

Ensure you do not have any other grid extensions installed at chrome://extensions

If you get a 404 from Google visiting the Chrome link, please clear your cookies and reload the page.

If you get "blocked by administrator" contact your IT department.
