### ISSUE TITLE
Screen Capture Mode isn't using the same ordering as regular mode

### ISSUE THREAD

**Issue by akx** [Fugiman/google-meet-grid-view#168]
**Is your feature request related to a problem? Please describe.**

Related to #163, it looks like the sort order computed into `ordering`:

https://github.com/Fugiman/google-meet-grid-view/blob/4885aa26e5fa7e68351b673b76bfa7b759076772/grid.user.js#L1273-L1275

is not used at all in Screen Capture Mode:

https://github.com/Fugiman/google-meet-grid-view/blob/4885aa26e5fa7e68351b673b76bfa7b759076772/grid.user.js#L1322-L1323

Instead, the ordering is specified by `screenCaptureModeAllocations`: https://github.com/Fugiman/google-meet-grid-view/blob/4885aa26e5fa7e68351b673b76bfa7b759076772/grid.user.js#L1198

**Describe the solution you'd like**

For transformed (Last, First) names to be used for ordering both in regular mode and screen capture mode.

**Describe alternatives you've considered**

--

**Comment by Eagle-Man** [comment]
Seconded!

**Comment by Fugiman** [comment]
Screen capture mode is intended for broadcast productions that require users to always occupy the same part of the screen. To support this it sorts by when a user joined the meeting.

It will never sort by name. If you want sorting by name do not use screen capture mode.

**Comment by akx** [comment]
Could this be an option, though? 

The use case here was to screen-record a graduation that occurred on Google Meet due to COVID-19, with all students' names in surname-alphabetical order.
