### ISSUE TITLE
Presenting creates hall of mirrors effect

### ISSUE THREAD

**Issue by mrussellcds** [Fugiman/google-meet-grid-view#171]
_Before opening an issue, please check the existing open issues to see if somebody has already reported it! If something is horribly wrong, like all videos showing up in a single column, chances are somebody already reported it. Please reply in that issue instead._

**Describe what is broken**
When presenting the entire screen so that viewers can see a separate window and the Google Meet window, it creates a picture-in-picture of the Grid View that seems to go to infinity, leading to a Hall of Mirrors effect that is really distracting. We tried this on three computers with 3 Google accounts, and experienced the same thing each time. 

**Expected behavior**
I hope that this can be resolved so that presenters can share the entire screen (multiple windows, including Google Meet) without this problem. 

**Screenshots**
<img width="1278" alt="Screen Shot 2020-05-27 at 11 35 10 AM" src="https://user-images.githubusercontent.com/66074592/83179671-8c498100-a0df-11ea-9e01-a4fadf6db2de.png">
<img width="1274" alt="Screen Shot 2020-05-27 at 11 39 32 AM" src="https://user-images.githubusercontent.com/66074592/83179679-910e3500-a0df-11ea-9676-cbdb393a717b.png">

**Software used:** 
 - OS [e.g. Windows 10]: El Capitan 10.11.6, Mac OS Mojave 10.14.6
 - Browser [e.g. Chrome, Firefox]: Chrome Version [e.g. 22]: 81.0.4044.138, Version 83.0.4103.61
 - Extension [e.g. Official Chrome Extension, Tampermonkey]: GridView
 - Grid View Version [e.g. 1.19, 1.23]: version installed May 25, 2020

**Additional context**

**Comment by Eagle-Man** [comment]
@mrussellcds I think this is not a problem with the extension, but is the expected result of displaying your own Meet screen.  Does this happen when you are displaying something that is NOT your Meet screen?

To avoid this, try the following options:
- if you would like to show a web page within the same browser window as your Meet, use the Chrome Tab presentation option to show only that tab.
- if you would like to show another application, use the Window presentation option to select the application window you would like to share.
- if you would like to display the entire screen, but still see the Meet, I would recommend joining the same Meet on two separate devices.
- change your "own presentation behavior" in the Advanced Settings.

**Comment by mrussellcds** [comment]
I wouldn't call it "expected behavior" because it didn't happen with the old version of Grid View until we updated on May 25. Prior to that, the teacher in the images used GridView with Meet with her class daily in this manner so that the class could see each other while also seeing what the teacher presented in a separate window. I'm trying to figure out why this isn't possible anymore-- when it was possible last week, and for months prior. 

The issue isn't just the presenter being able to see the entire group, but the rest of the group being able to see the entire group during a presentation. FWIW, all of the students also have Grid View installed, but they do not present or share their screens.

**Comment by Eagle-Man** [comment]
It likely didn't happen because earlier versions did not display what you, the presenter, is presenting.  This was added in v1.33 by user request.  As of v1.34, it is a setting which you can turn on and off.  Try turning it off to return to the old behaviour.

**Comment by Fugiman** [comment]
You likely have v1.33 installed which added your own presentation to the grid by default. Please upgrade to v1.34 (May 28th) which makes it an opt-in advanced setting instead.
