### ISSUE TITLE
Highlight feature rectangle isn't uniform

### ISSUE THREAD

**Issue by MarcAnt01** [Fugiman/google-meet-grid-view#172]
_Before opening an issue, please check the existing open issues to see if somebody has already reported it! If something is horribly wrong, like all videos showing up in a single column, chances are somebody already reported it. Please reply in that issue instead._

**Describe what is broken**
When a user is highlighted the upper and the vertical sides of the rectangle are static while the bottom side is flashing

**Expected behavior**
Choose a kind of behavior and make it consistent for the whole rectangle

**Screenshots**

**Software used:**
 - OS Windows 10 
 - Browser Edge
 - Version 83.0 Beta
 - Extension Chrome Web Store extension
 - Grid View Version 1.34

**Additional context**
Not needed

**Comment by sreyemnayr** [comment]
I've seen this as well, it seems to be an artifact of the native "tiled" view

**Comment by Fugiman** [comment]
This is due to odd z-indexing rules that's hard to work around. I can try to improve it, but the core of it is that the name/mic status has a mostly transparent black gradient background that is getting overlaid on top of the highlight rectangle. I can't move the highlight rectangle above it easily as that would cause issues with the "pin/mute/hide/remove" overlay on each video.

Again, I'll look into it, but it's low priority and might not be fully fixable.

**Comment by MarcAnt01** [comment]
> This is due to odd z-indexing rules that's hard to work around. I can try to improve it, but the core of it is that the name/mic status has a mostly transparent black gradient background that is getting overlaid on top of the highlight rectangle. I can't move the highlight rectangle above it easily as that would cause issues with the "pin/mute/hide/remove" overlay on each video.
> 
> Again, I'll look into it, but it's low priority and might not be fully fixable.

If it's hard to fix, what about using just the bottom bar instead of the whole square?

**Comment by sreyemnayr** [comment]
That still wouldn't change the fact that the native code is drawing its own bar. The strange thing is that it occasionally just doesn't go away. But totally agree that it's a low-priority issue.

**Comment by Fugiman** [comment]
Fixed in v1.35
