### ISSUE TITLE
Grid View is not running on this page

### ISSUE THREAD

**Issue by PeterFont123** [Fugiman/google-meet-grid-view#173]
_Before opening an issue, please check the existing open issues to see if somebody has already reported it! If something is horribly wrong, like all videos showing up in a single column, chances are somebody already reported it. Please reply in that issue instead._

**Describe what is broken**
Gridview is not working. Have uninstalled all older versions, and Installed the one from Chris Gamble. I have updated chrome, deleted cache/cookies, uninstalled, restarted, reinstalled, etc. etc. I have tried seemingly every combination I can think of and every time I go to use it it says

"Grid View is not running on this page"
Version is v1.34.0 

What do I do here???

**Expected behavior**

**Screenshots**

**Software used:**
 - OS [e.g. Windows 10]:
 - Browser [e.g. Chrome, Firefox]:
 - Version [e.g. 22]:
 - Extension [e.g. Official Chrome Extension, Tampermonkey]:
 - Grid View Version [e.g. 1.19, 1.23]:

**Additional context**

**Comment by Fugiman** [comment]
Grid view only runs when you are in a meeting on meet.google.com

Please go to meet.google.com and enter a meeting (and join it) before trying to use the extension

**Comment by PeterFont123** [comment]
It's doing it while I'm in the grid though. It's not working in Google meet

**Comment by rmusalMC** [comment]
Are you on latest chrome?
Are you sure you don't have multiple versions of the extension installed?

_____________________________
Richard A. Musal, M.A., M.S., P.D.
Director of Client Services & Operations, ITS
Manhattan College
Riverdale, NY 10471
Phone: 718-862-7933
richard.musal@manhattan.edu
www.manhattan.edu
manhattan.edu/its
itsblog.manhattan.edu

**Comment by PeterFont123** [comment]
would it be helpful If I sent you a screenshot of exactly what I'm seeing?

In google meet, grid view installed, still saying "Grid View is not running
on this page
v1.34.0 Source code available on GitHub
<https://github.com/Fugiman/google-meet-grid-view>" no matter how many
times I install, uninstall, reinstall, nothing old is installed, etc, etc.
