### ISSUE TITLE
Have to edit settings on every meeting

### ISSUE THREAD

**Issue by romanadam91** [Fugiman/google-meet-grid-view#175]
If I join a meeting and change the settings as needed like obscure, highlight speaker or include yourself in grid and leave the meeting and join again the settings are gone. I have to do this again and again instead of doing it once and leave it as it is. The settings should be universal for all the meetings once I do that. I hope you get this fixed. Thanks in advance. 

Chrome Version 83.0.4103.61 (Official Build) (64-bit)
Mac os Catalina 10.15.4
Grid Ver: 1.34.0

**Comment by Fugiman** [comment]
The extension stores all your settings in "Local Storage" and should persist between meetings. Do you "clear browsing data" often, browse in incognito mode, or have an extension that blocks or clears local storage?

**Comment by romanadam91** [comment]
I am sorry. I do clear chrome history and data often. Is this the reason why it clears the settings every time ? Please also help me if there is any other way to save the settings and clearing history data won't effect the same. 

Thank you again for replying.

**Comment by Eagle-Man** [comment]
Additionally, if your organization manages your Chrome account, they may force Chrome to run in incognito mode, disable LocalStorage, or clear browser data each time the browser closes.  In this case, there may not be a remedy besides convincing your tech department to change these settings.

**Comment by romanadam91** [comment]
I use this for personal use and I clear the LocalStorage just to make sure things work smooth and fresh cache and files load on the browser.

**Comment by Fugiman** [comment]
No, there is no other way to save the settings. If you clear local storage on the `meet.google.com` domain you'll need to set the settings again.

**Comment by romanadam91** [comment]
Alright! Will take care of this. Thank you so much. 👍
