### ISSUE TITLE
grid view extensions

### ISSUE THREAD

**Issue by 201116L** [Fugiman/google-meet-grid-view#176]
Ho aggiunto l'estensione a grid view come consigliato, ma non riesco a visualizzare sullo schermo più di sedici utenti alla volta, mi compare questa scritta che riporto letteralmente:
Multiple Grid View extensions detected, please unistall duplicates.
Come posso fare per visualizzare più persone alla volta (almeno trenta)
Grazie

**Comment by rmusalMC** [comment]
Devi levare uno degli extension. Quello più vecchio.

_____________________________
Richard A. Musal, M.A., M.S., P.D.
Director of Client Services & Operations, ITS
Manhattan College
Riverdale, NY 10471
Phone: 718-862-7933
richard.musal@manhattan.edu
www.manhattan.edu
manhattan.edu/its
itsblog.manhattan.edu

**Comment by Martibosc** [comment]
Stessa cosa mi succede, ma come/dove tolgo unextension?

**Comment by rmusalMC** [comment]
Prova questo: https://manhattan.teamdynamix.com/TDClient/1932/Portal/KB/ArticleDet?ID=108737
E in ingelese.

**Comment by Martibosc** [comment]
E'sicuro? Mb
    Il venerdì 29 maggio 2020, 21:07:39 CEST, Rich Musal <notifications@github.com> ha scritto:  
 
 


Prova questo: https://manhattan.teamdynamix.com/TDClient/1932/Portal/KB/ArticleDet?ID=108737
E in ingelese.

**Comment by Martibosc** [comment]
Grazie, fatto 


Martina Boscaro
Inviato da iPhone

**Comment by rmusalMC** [comment]
Buonissimo!

_____________________________
Richard A. Musal, M.A., M.S., P.D.
Director of Client Services & Operations, ITS
Manhattan College
Riverdale, NY 10471
Phone: 718-862-7933
richard.musal@manhattan.edu
www.manhattan.edu
manhattan.edu/its
itsblog.manhattan.edu
