### ISSUE TITLE
No Names in Gridview 

### ISSUE THREAD

**Issue by shamr0k21** [Fugiman/google-meet-grid-view#177]
I can no longer see the names of the scholars with their pictures in my class, or highlight the speaker. I uninstalled and reinstalled gridview several times this week tp repair the issue, other issues I was having were reparied by doing this but not this issue. It is very difficult to see who is in the class, and speaking without their names with their pictures and the highlight feature. I do know there is a dropdown on the side to see who is in the class, but I need the names to be with their pictures too. It was fine since March. It began this week.

**Comment by Fugiman** [comment]
Please make sure you installed the extension from the following links
Chrome: https://chrome.google.com/webstore/detail/google-meet-grid-view/kklailfgofogmmdlhgmjgenehkjoioip
Firefox: https://addons.mozilla.org/en-US/firefox/addon/google-meet-gridview

Please also make sure you do not have any other grid view extensions installed. You can check this at chrome://extensions and can remove any duplicates with the "remove" button. If you're unsure, remove them all and then reinstall the extension from the link above.

Finally make sure you've enabled the grid view by clicking the extension icon and verifying "Enable Grid View" is checked.

Grid View explicitly forces names to be visible so if you've followed all those steps and it still isn't fixed please provide an image of the meeting (with faces redacted)

**Comment by shamr0k21** [comment]
Good morning,
I couldn't send you the image till I had a live class. I have followed the
steps provided. This is what I am seeing...
Also I am unable to highlight the speaker.

**Comment by Fugiman** [comment]
You can not attach images in reply to github issues. Either reply to the issue on github and attach the image there, or send the image directly to fugiman47+grid-view-extension@gmail.com
