### ISSUE TITLE
Can't remove the old extension

### ISSUE THREAD

**Issue by cinluu** [Fugiman/google-meet-grid-view#183]
I keep getting an error messaging saying I have 2 of the extensions installed. I've tried for over a week now to remove the old grid extensions but it's not removable. There's no option to remove it. I'm using an Asus Chromebook.

**Comment by Fugiman** [comment]
You can see which extensions you have installed at chrome://extensions and there should be a "Remove" button. If there is not, or if it doesn't work, the extension was likely installed by your organization and you'll need to contact your IT department.

**Comment by cinluu** [comment]
Ahhh that makes sense! It’s a school account and it is on both my daughters
chrome account but not my personal! Thanks I’ll let the school know to
remove it
