### ISSUE TITLE
Option to fit to cell of fill for participants videos

### ISSUE THREAD

**Issue by nbcraft** [Fugiman/google-meet-grid-view#184]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to see the entire video feed of participants rather than cropped and zoomed to fill their cells, just like I see my own video fully.

(`Screen Capture Mode` kinda accomplishes that, but removes names and other visuals, and could use more screen estate).

**Describe the solution you'd like**
An option somewhere (maybe in advanced settings?) to switch between fill or fit to cell.

**Describe alternatives you've considered**
No alternatives, except maybe have a setting for own video, and a setting for participants.

**Additional context**
N/A

**Comment by Fugiman** [comment]
The crop & zoom is controlled by google meet and isn't something I can reasonably control, especially considering videos may not be 16:9

**Comment by nbcraft** [comment]
Thank you for taking a look 🙏 .

I don't know the details of the codebase so I understand that this can be a tough one.
`Screen Capture Mode` seemed like it was doing this though (but was also removing too much of the interface for standard use).

Also about 16:9, I was more think a generic `fit to cell` for all sizes, but again I understand if it's a tough one.
