### ISSUE TITLE
Grid extension.  I have uninstalled and reinstalled but am getting a "uninstall duplicate copies" error message.  I cannot see more than 16 people in grid.  I am using a MacBook Pro and a HP chrome book

### ISSUE THREAD

**Issue by jbart64** [Fugiman/google-meet-grid-view#185]
_Before opening an issue, please check the existing open issues to see if somebody has already reported it! If something is horribly wrong, like all videos showing up in a single column, chances are somebody already reported it. Please reply in that issue instead._

**Describe what is broken**
A clear and concise description of what isn't working.

**Expected behavior**

**Screenshots**

**Software used:**
 - OS [e.g. Windows 10]:
 - Browser [e.g. Chrome, Firefox]:
 - Version [e.g. 22]:
 - Extension [e.g. Official Chrome Extension, Tampermonkey]:
 - Grid View Version [e.g. 1.19, 1.23]:

**Additional context**

**Comment by rmusalMC** [comment]
Did you try to clear cache?

_____________________________
Richard A. Musal, M.A., M.S., P.D.
Director of Client Services & Operations, ITS
Manhattan College
Riverdale, NY 10471
Phone: 718-862-7933
richard.musal@manhattan.edu
www.manhattan.edu
manhattan.edu/its
itsblog.manhattan.edu

**Comment by Fugiman** [comment]
Please visit chrome://extensions and click "remove" on any grid view extensions, then install https://chrome.google.com/webstore/detail/google-meet-grid-view/kklailfgofogmmdlhgmjgenehkjoioip

**Comment by Eagle-Man** [comment]
Is your Chrome account managed by your organization?  If so, you will need to get your IT department to remove the extensions or they will continue to force install when you run Chrome.

**Comment by jbart64** [comment]
Thank you! I will follow up with them!
