### ISSUE TITLE
la griglia non funziona

### ISSUE THREAD

**Issue by Ironfrancy** [Fugiman/google-meet-grid-view#186]
_Before opening an issue, please check the existing open issues to see if somebody has already reported it! If something is horribly wrong, like all videos showing up in a single column, chances are somebody already reported it. Please reply in that issue instead._

**Describe what is broken**
A clear and concise description of what isn't working.

**Expected behavior**

**Screenshots**

**Software used:**
 - OS [e.g. Windows 10]:
 - Browser [e.g. Chrome, Firefox]:
 - Version [e.g. 22]:
 - Extension [e.g. Official Chrome Extension, Tampermonkey]:
 - Grid View Version [e.g. 1.19, 1.23]:

**Additional context**

**Comment by rmusalMC** [comment]
Come non funziona?
-----------------------
*Richard A. Musal, M.A., M.S., P.D.*
*Director of Client Services & Operations, ITS*

Riverdale, NY 10471
Phone: 718-862-7933
richard.musal@manhattan.edu
www.manhattan.edu

<http://itsblog.manhattan.edu/>
<http://manhattan.edu/its>

*-Have a question? * Check our Knowledge Base
<https://manhattan.teamdynamix.com/TDClient/KB/Default>

Check on your tickets here: Link to your ITS tickets
<https://manhattan.teamdynamix.com/TDClient/Requests/TicketRequests/>
Link to ITS Service Catalog
<https://manhattan.teamdynamix.com/TDClient/Requests/ServiceCatalog>

**Comment by MarcAnt01** [comment]
@Ironfrancy compila il template, con report di questo tipo nessuno può aiutarti. Inoltre posta screenshot o spiegazioni accurate del problema in Inglese
