### ISSUE TITLE
Issues with Gmail (slowness) when using gridview

### ISSUE THREAD

**Issue by Leilapostner** [Fugiman/google-meet-grid-view#187]
**Describe what is broken**
With the extension gmail is incredibly slow takes about 10-15 seconds to lead a new email, internal IT suggested deinstalling the gridview app and now it works please do fix the issue so I can use it again 

**Software used:**
 - OS macos Mojave Version 10.14.6
 - Browser Chrome, 
 - Version :Version 83.0.4103.61 (Official Build) (64-bit)
 - Extension [e.g. Official Chrome Extension, 
 - Grid View Version newest one

**Comment by Fugiman** [comment]
The extension does not run or modify gmail in any way, so I'm unsure why it would affect gmail.
