### ISSUE TITLE
Swedish = "se"

### ISSUE THREAD

**Issue by lerklompen** [Fugiman/google-meet-grid-view#19]
Swedish should be "se", instead of "sv".

Regards
Mattias

**Comment by Fugiman** [comment]
Both Chrome and Firefox use `sv` as the code for Swedish. Where are you seeing `se` be used?

**Comment by lerklompen** [comment]
Sorry, my bad!
According to java standard  it should be "sv-SE". Initially it didn't work using only "sv", or there was some kind of caching going on when loading localy - please disregard.
