### ISSUE TITLE
I'm a completly newbie, please help me out!

### ISSUE THREAD

**Issue by TeacherGus** [Fugiman/google-meet-grid-view#190]
I use google meet grid view for teaching. I'm having an issue that the participants of my meeting appear one on the top of the other. I cannot see them in grid anymore. I tried to solve in the advanced settings, but without any success: I still see them like a list.

**Comment by Jorrmungandr** [comment]
I believe that is happening because of meet's layout update yesterday, let's wait until the developers see the issue and solve it.

**Comment by Eagle-Man** [comment]
@TeacherGus What version of the extension do you have?  Also, ensure that no other unofficial Grid View extensions are installed as they conflict and are not updating regularly.
