### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by CCreativeCND** [Fugiman/google-meet-grid-view#192]
**Is your feature request related to a problem? Please describe.**
It is annoying to have a bright white screen when you are in a meeting.

**Describe the solution you'd like**
Inject CSS into the page to turn the background and other elements dark.

**Describe alternatives you've considered**
I tried using Dark Reader, but it slows everything down.

**Additional context**
The CSS should be pretty easy as it is just static, but I don't know how Google does all of their class naming. I can help implement this if needed.

**Comment by Fugiman** [comment]
This is not a dark theme extension and I will not add a dark theme to it.
