### ISSUE TITLE
Layout with multiple presentations

### ISSUE THREAD

**Issue by MarcAnt01** [Fugiman/google-meet-grid-view#194]
**Is your feature request related to a problem? Please describe.**
Meet introduced the possibility to have multiple users presenting

**Describe the solution you'd like**
Uniform the dimensions of the rectangles where users are presenting

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/43090263/84014712-1238b800-a97b-11ea-93cb-8a271a712be4.png)

**Comment by Fugiman** [comment]
multiple users can present but there's always a primary presentation, as show in the top left corner of "Matteo is presenting". The primary presentation will be the one that is enlarged, which is expected behavior. If you'd like to focus a different presentation you can use the pin feature.
