### ISSUE TITLE
Cannot hide bottom bar when in full screen

### ISSUE THREAD

**Issue by MarcAnt01** [Fugiman/google-meet-grid-view#195]
_Before opening an issue, please check the existing open issues to see if somebody has already reported it! If something is horribly wrong, like all videos showing up in a single column, chances are somebody already reported it. Please reply in that issue instead._

**Describe what is broken**
Bottom bar auto-hiding. The only way to hide it is the esc key

**Expected behavior**
Hide

**Screenshots**
Not needed

**Software used:**
 - OS Windows10 2004
 - Browser Microsoft Edge Beta 
 - Version 84.0
 - Edge add-ons store extension
 - Grid View Version 1.35

**Additional context**
Not applicable

**Comment by Fugiman** [comment]
It hides fine for me. Make sure you don't have it set to always show in advanced settings?

**Comment by MarcAnt01** [comment]
No, the setting is set to default and I still can't hide it, maybe it depends on the browser?

**Comment by MarcAnt01** [comment]
@Fugiman can you reopen it. I am on v.1.37 and still happening

**Comment by ben8p** [comment]
Same here,
There's no way to hide it...

**Comment by gbdav** [comment]
Same here,
help please ToT

**Comment by oleksiyserg** [comment]
same problem for me. please reopen

**Comment by MarcAnt01** [comment]
@BukeMan I cannot reopen issues closed by project owners
