### ISSUE TITLE
New checkboxes (awesome ideas) toggle the grid view when clicked

### ISSUE THREAD

**Issue by sreyemnayr** [Fugiman/google-meet-grid-view#2]
The clicking of the checkboxes is bubbling up to the grid icon... I'll try to have a look over the weekend to see if I can give you a PR to fix it. Just wanted to make sure it was on your radar, though :)

**Comment by sreyemnayr** [comment]
It also appears that a certain volume level is required to trigger the highlight?

**Comment by Fugiman** [comment]
Fixed in v1.6, thanks for the report!
