### ISSUE TITLE
Grid View Broke/Not working

### ISSUE THREAD

**Issue by romanadam91** [Fugiman/google-meet-grid-view#202]
**Describe what is broken**
Grid view is not working seems like google changed the coding and view of the way the participants are displayed on the screen. Request you to please check the same and update this. Looking for a positive response from you. Attached the screenshot for reference as well. Thank a lot.

**Screenshots**
![Screenshot 2020-06-15 at 10 13 56 AM](https://user-images.githubusercontent.com/64604081/84619157-f6409380-aef1-11ea-9e72-a73ae2212fa2.png)

**Software used:**
 - OS: MacOS Catalina Version 10.15.5
 - Browser: Chrome
 - Version: Version 83.0.4103.97 (Official Build) (64-bit)
 - Extension: Grid View
 - Grid View Version: 1.35.0

**Comment by Yukeechan** [comment]
Same here. Please help.

**Comment by ZZZ-ENG623** [comment]
same here !

**Comment by hxghf** [comment]
suddenly again after the google meet updated the extension has broke i have v1.35.0 and all the videos come but they are on top of each other and very tiny i reinstalled relaunched restarted changed settings nothing worked and its the same thing

**Comment by ZZZ-ENG623** [comment]
Pls give a solution for the problem

**Comment by minakshipodar** [comment]
please give us a solution as i being a teacher this is a serious cause of concern

**Comment by brijesh101010** [comment]
Same problem here i dont know how to solve.

**Comment by sayedarifuddin** [comment]
Same issue here.

**Comment by vrruzi** [comment]
Hello, Same in here, and It affected not all of our teachers but many of them. Chrome Version is same in both situation (with the ones working and with the ones not working)
Version 83.0.4103.97 (Official Build) (64-bit)
Win10

**Comment by Martijnvmoock** [comment]
Same problem, on Chrome with mac

**Comment by heillos** [comment]
I confirm :( In Poland this is classification conferences time and I hope it will be fixed soon

**Comment by RiZKiT** [comment]
I expect it might be related to an official change in Google Meet, so the developer needs to figure out what changed, might take some time to investigate.

**Comment by TomasLopezValcarcel** [comment]
Same here. I currently have the extension disabled and I'm using Google's own tiled view until this is fixed.

**Comment by smufo** [comment]
Guys, he is sleeping, please stop creating new posts.

**Comment by sarayu1971** [comment]
> **Describe what is broken**
> Grid view is not working seems like google changed the coding and view of the way the participants are displayed on the screen. Request you to please check the same and update this. Looking for a positive response from you. Attached the screenshot for reference as well. Thank a lot.
> 
> **Screenshots**
> ![Screenshot 2020-06-15 at 10 13 56 AM](https://user-images.githubusercontent.com/64604081/84619157-f6409380-aef1-11ea-9e72-a73ae2212fa2.png)
> 
> **Software used:**
> 
> * OS: MacOS Catalina Version 10.15.5
> * Browser: Chrome
> * Version: Version 83.0.4103.97 (Official Build) (64-bit)
> * Extension: Grid View
> * Grid View Version: 1.35.0

same issue here Please help

**Comment by AdamReece-WebBox** [comment]
Same here, though if you turn off grid view the vanilla tiled view now shows more than 4 people. (Though not as well as this extension did.)

**Comment by anne-nelson** [comment]
Everyone adding new comments just to say "me too" doesn't help, it's just going to spam his inbox. Just give a 👍 on the original post.

**Comment by agomism** [comment]
Option to Hide "presentation" and add my own video to the grid don't work either.
![image](https://user-images.githubusercontent.com/63906830/84639492-c052dd80-aef8-11ea-895a-417b126aea92.png)

**Comment by FrancescoPiccolo** [comment]
Same Problem Grid View broken

**Comment by paulpav** [comment]
Same problem. Worked for a bit today ... then stopped ... then came back ... but gone again. Have removed from chrome and reinstalled.

**Comment by tankrizzo** [comment]
Please stop commenting that this is broken or "same issue". Give a +1 to the original issue. This is not Facebook.

**Comment by EnzoLiv** [comment]
This issue happended in the unoriginal version. Now is in the original version.

**Comment by Fugiman** [comment]
v1.36 is done and going through the release process. Please update when it is available (firefox already is) and let me know if it doesn't solve the issue.

**Comment by tiga354** [comment]
Same issue with me!

**Comment by sayedarifuddin** [comment]
Appreciate! 👏 How about Microsoft Edge Extension? https://microsoftedge.microsoft.com/addons/detail/google-meet-grid-view/ogbbehbkcmdciebilbkpjgopohnpfolj

**Comment by sayedarifuddin** [comment]
> v1.36 is done and going through the release process. Please update when it is available (firefox already is) and let me know if it doesn't solve the issue.

Appreciate! 👏 How about Microsoft Edge Extension? https://microsoftedge.microsoft.com/addons/detail/google-meet-grid-view/ogbbehbkcmdciebilbkpjgopohnpfolj

**Comment by sopos** [comment]
> v1.36 is done and going through the release process. Please update when it is available (firefox already is) and let me know if it doesn't solve the issue.

Looks like 1.36 works, at least in FF. Thanks a lot!

**Comment by pbanks1** [comment]
Any idea how long it takes for extensions to filter through for chrome?

**Comment by ruruboxer** [comment]
Grid view is the greatest thing that ever happened to Meet. It is broken right now as you can see. I appreciate your help in fixing it. I would also like to donate money to you as you deserve!

**Comment by billhoffman** [comment]
For me 1.36 is still not working. Tried chrome and firefox on windows.

**Comment by oboylejf** [comment]
Any update on a chrome fix for 1.36?

**Comment by debarmv** [comment]
Same problem here! Everything is updated and the Grid View looks like the pictures posted here.

**Comment by seigel** [comment]
Confirm

**Comment by tanderson1966** [comment]
eagerly awaiting 1.36.0 ;) especially as i have abundant large school meetings this week........ :D

**Comment by yuhaian** [comment]
Seems Chrome Web Store list this extension for v1.35 for now. I'm waiting for the release process to complete to use v1.36 for chrome.

**Comment by Fugiman** [comment]
I have no control over how long it takes for Chrome & Microsoft Edge to approve the new version. It can be as fast as a few hours or as long as a week.

**Comment by tanderson1966** [comment]
roger that! ty

**Comment by rachelgues** [comment]
same !!!!!

**Comment by mason195** [comment]
He posted update 1.36 about 8 hours ago. We're just waiting for Chrome to accept it and add it to the official release.

**Comment by syoung-quizlet** [comment]
What do you all gain from the Gridview extension vs the default tiled view?  Is it visibility into more than 16 people?

**Comment by purp** [comment]
@syoung-quizlet Yes, this extension adds the ability to apply much finer grained control to who you see in the meeting and how you see them. Google is catching up, but doesn't provide things like:

* See everyone in the meeting, filtered by who's showing video (or not)
* See yourself in the grid
* Control how you see presentations in grid view, with separate controls for how *you* see your own presentations
* Also seems to give higher quality video overall; it comes at a cost of running the CPU hard

I find that I like this extension for meetings with more than 4-6 people, and I tend to turn it off when it's < 6 people.

**Comment by pbanks1** [comment]
This is without a doubt the greatest extension out there. We could not have functioned without it. Regularly have 100's of people on a meet and this allows us to see them all! Astonishing piece of engineering.
Thank you so much for developing and updating so often. Really hoping it will be up and running again soon. 👍 
Thanks!

**Comment by jmota** [comment]
![image](https://user-images.githubusercontent.com/4175742/84702735-1d648880-af25-11ea-9298-d6b2c792e61c.png)
![image](https://user-images.githubusercontent.com/4175742/84702757-23f30000-af25-11ea-87a4-61cfad8fea7f.png)

**Comment by rogersandro** [comment]
DOsen´t work! it´s the same here!!!!!!!!!!!!!!

**Comment by pablogirado** [comment]
No funciona nuevamente, que lastima.

**Comment by PhilippeGi** [comment]
Used to work properly like everybody else. So I've downloaded and installed v1.36 manually but it does not work at all. I'm working from a chromebook. Once installed and I click on the grid view extensions icon, I get an empty contextual menu. 

Chrome: Version 83.0.4103.97 (Build officiel) (64 bits)

There might be something to fix in 1.36 so that it could be offically released. Waiting for 1.37 :)

**Comment by Yukeechan** [comment]
Same here. version 1.36 still not working. And it would make google meet to be unresponsive once we clicked on the grid view. Please help. Thanks.

**Comment by chuanzgh** [comment]
Chrome Web Store updated to 1.36.0

**Comment by friederikewild** [comment]
Got version 1.36 on Chrome automatically and magically got a grid again 🙏 🎉  Thanks for fixing

**Comment by RiZKiT** [comment]
v1.36.0 works for me in Vivaldi (Chrome based) on MacOS. 

But I experienced one hang/crash of the tab when toggle mute/video, might be related to the plugin or not. After reopening the tab everything worked again.

Besides I feel a bit sorry for the developer, because all of the end users raising new tickets without reading the rules or adding "me too" comments. I'm not used to this on github.

**Comment by sayedarifuddin** [comment]
> v1.36.0 works for me in Vivaldi (Chrome based) on MacOS.
> 
> But I experienced one hang/crash of the tab when toggle mute/video, might be related to the plugin or not. After reopening the tab everything worked again.
> 
> Besides I feel a bit sorry for the developer, because all of the end users raising new tickets without reading the rules or adding "me too" comments. I'm not used to this on github.

Mine still not working in Microsoft Edge Canary, I'm using the Chrome Web Store Extension (v1.36.0) as Microsoft Edge Add-ons didn't received the update yet. https://microsoftedge.microsoft.com/addons/detail/google-meet-grid-view/ogbbehbkcmdciebilbkpjgopohnpfolj?hl=en-US

**Comment by vretamal** [comment]
> What do you all gain from the Gridview extension vs the default tiled view? Is it visibility into more than 16 people?

Sort the members alphabeticly, so for me it's more confortable to see who is in the meeting and who is missing. Also is more confortable than the default grid view.
Brave (chromium based) still have the 1.35.0, so I'll have to wait.

**Comment by shalmaleeC** [comment]
Google chrome grid view extension not working properly.  When you hit grid view the students came up in a straight line down the middle of the computer. Even Can't see myself in the window.
