### ISSUE TITLE
gid view is not working

### ISSUE THREAD

**Issue by HABEEBA-PROG** [Fugiman/google-meet-grid-view#204]
_Before opening an issue, please check the existing open issues to see if somebody has already reported it! If something is horribly wrong, like all videos showing up in a single column, chances are somebody already reported it. Please reply in that issue instead._

**Describe what is broken**
A clear and concise description of what isn't working.

**Expected behavior**

**Screenshots**

**Software used:**
 - OS [e.g. Windows 10]:
 - Browser [e.g. Chrome, Firefox]:
 - Version [e.g. 22]:
 - Extension [e.g. Official Chrome Extension, Tampermonkey]:
 - Grid View Version [e.g. 1.19, 1.23]:

**Additional context**

**Comment by smufo** [comment]
Copy of #202

**Comment by rachelmauloni** [comment]
Grid view is not working for me either. I have tried uninstalling and reinstalling and then restarting my computer but I haven't had any luck.

**Comment by anne-nelson** [comment]
@rachelmauloni Please don't comment on an issue just to say "me too", it just spams the owner.

**Comment by HABEEBA-PROG** [comment]
ME TOO
