### ISSUE TITLE
1.35.0 version is broken

### ISSUE THREAD

**Issue by luispla22** [Fugiman/google-meet-grid-view#205]
It does not show all the participants and the people who are shown appears in a very strange form that is so anoying. It seems as the code has been changed.
Please fix it.
Thanks.

![Sin título](https://user-images.githubusercontent.com/66942876/84635968-46205a00-aef4-11ea-9695-1771263989f2.jpg)

**Comment by smufo** [comment]
Copy of #202

**Comment by HyperLynk** [comment]
I am having the same issue.

**Comment by RiZKiT** [comment]
> Before opening an issue, please check the existing open issues to see if somebody has already reported it! If something is horribly wrong, like all videos showing up in a single column, chances are somebody already reported it. Please reply in that issue instead.

**Comment by Fugiman** [comment]
(Maybe) fixed in v1.36
