### ISSUE TITLE
Make it play nicer with screen sharing

### ISSUE THREAD

**Issue by marcofugaro** [Fugiman/google-meet-grid-view#21]
Hey there are some issues with this script and the share screen feature. First of all the shared screen doesn't enlarge (that makes sense). Then when I try to deactivate the layout, it doesn't work. I had to toggle off the extension to make it work.

How to reproduce the bug:

1. Enter in call with grid view
1. Someone starts sharing screen
1. Sharing sreen is small because of grid view
1. Try to disable grid view layout
1. It's bugged

**Comment by Fugiman** [comment]
Thanks for the report. I've had a lot of trouble reproducing this reliably, but hope that v1.12 will fix the issue. Please let me know if it doesn't!

As for screen sharing not expanding the video: v1.9 supports pinning videos which includes the share screen. Pinning will increase the size of the video to over 1/4 of your screen (half the height and half the width of your screen). As of 1.12 shared screens will do this by default, assuming you haven't pinned anyone else. Hopefully this meets your needs.

**Comment by rogerl19** [comment]
Just talked to a user in our organization who faced something similar.  In a Google Meet with 30 people, he needed to see the presentation being shared in Meet's native Spotlight mode.  However, when he tried to deactivate Grid view (not disable the extension), the elements did not return to the proper Spotlight mode.  He had to refresh the tab and Re-Join the meeting.

He has not been able to reproduce and smaller meetings of 15 people did not have issues.

This maybe a JS / DOM issue with the rendering.  Note user was on an Acer Chromebook Spin 13.

Maybe v1.12 will lessen this issue as user won't need to switch in and out of grid view.

Thanks for all the hard work.  This has been amazing.

**Comment by greznik** [comment]
I had the same exact issue as @rogerl19 but with small meetings and on a Macbook Pro running Catalina. It seems that when a person **shares something and you pin it, then they unshare and someone else starts sharing, when you try to pin the new share it will not let you**, but rather bug out or only show as part of the grid.

**Comment by Fugiman** [comment]
I have still been unable to reproduce this issue, and hopefully with the recent changes it's fixed. Feel free to comment or open a new issue if you experience it again.
