### ISSUE TITLE
Grid view is showing participant in vertical order instead of tiled view

### ISSUE THREAD

**Issue by Ruchi-T** [Fugiman/google-meet-grid-view#215]

**Comment by chirscalalang** [comment]
I also have the same issue. Tried reinstalling a couple of times and still at vertical.

**Comment by RiZKiT** [comment]
Please, stop creating new issues for an already known problem: https://github.com/Fugiman/google-meet-grid-view/issues/202

**Comment by Fugiman** [comment]
If you have v1.35 please update. If you have v1.36 please describe what you experience in as much detail as possible and with images in #214
