### ISSUE TITLE
Update 1.36 don't work

### ISSUE THREAD

**Issue by Robinlocksleyy63** [Fugiman/google-meet-grid-view#216]
Over a number of participants Grid View crashes Meet

**Comment by ashokpjacob** [comment]
Chrome and Firefox freeze when extension is on

**Comment by Willsolucao** [comment]
No meu trabalho também, todos estão travando quando usam o grid na versão 1.36

**Comment by Fugiman** [comment]
If you have v1.35 please update. If you have v1.36 please describe what you experience in as much detail as possible and with images in #214
