### ISSUE TITLE
Grid view isn't working.

### ISSUE THREAD

**Issue by Hena766** [Fugiman/google-meet-grid-view#217]
I am a teacher and using Google meet for online classes. The extension "grid view" in gmeet is not working. No matter what option i clicked be it tile, spotlight,sidebar but it was always on AUTO during grid view extension which was a mess in my class. I have to disable my grid view extension then i could able to see, but that also only 16 at a time which is not feasible to me. I teach children of 8-9 years of age so i need to see their faces all the time. I have even tried to uninstall and reinstall the grid view extension but in vain. So plz resolve this issue as soon as possible. My all the other teachers also faced the same issue. Its really causes a lot of problem. I have even report a issue in meet with a screenshot. Solve this as soon as possible.

**Comment by 0bmxa** [comment]
>Before opening an issue, please check the existing open issues to see if somebody has already reported it! If something is horribly wrong, like all videos showing up in a single column, chances are somebody already reported it. Please reply in that issue instead.

**Comment by Pieter-N** [comment]
Also, please bear in mind that the developer does this in his spare time and free of charge. 
When you are so dependent of this extension, please consider the Sponsor button at the top of this page.

**Comment by Fugiman** [comment]
If you have v1.35 please update. If you have v1.36 please describe what you experience in as much detail as possible and with images in #214
