### ISSUE TITLE
Google meet crash due to grid view extension.

### ISSUE THREAD

**Issue by Pravin1001** [Fugiman/google-meet-grid-view#218]
The grid view extension was working smoothly until the update of 1.36...
The google meet crashes in all browsers like Firefox, Chrome and Edge too
Request you to Update the extension asap
Comment below if you too have the same problem..
If anyone got a solution please comment it below or mail me at avrs621kolaapravin@gmail.com
PLS HELP ME OUT I NEED TO GET MY STUDENTS ATTENDANCE ASAP IT IS OF TWO DAYS I AM UNABLE TO TAKE ATTENDANCE..
Screenshots couldn't be added...sorry

**Comment by Pravin1001** [comment]
PLEASE HELP ME OUT GUYZ...

**Comment by maxburboav** [comment]
Buenos días, efectivamente en Chrome no está funcionando la extensión "Meet Grid View"

**Comment by Willsolucao** [comment]
Na versão 1.36 trava onde trabalho também.

**Comment by CherylYui** [comment]
Grid view extension defect the Google Meet screen. It became lag and I cant look at my students at all. I cant even share my screen tomy students.

**Comment by joshsharrad** [comment]
Grid View Extension is completely broken in Google Chrome as of yesterday's update. Just crashes the Google Meet tab.

**Comment by Mennukido** [comment]
Same problem here. After 20 participants meet tab crashes. After disable the grid i was able to join meet again.

**Comment by vgisbert** [comment]
The same has happened to us both in chromebooks, in firefox and in google chrome 83.0.4103.97.
And we need it for school because our classes are 30 students.
Until a few days ago it worked.
We have put a query to Google and they indicate:
>>>>>>>>>>>>
I understand that you want to be able to use G Suite with the functionality of the Mosaic view since you used the GRID extension. Please note that this extension is not supported by G Suite, therefore we cannot assist you in the event that the extension stops working.

The only thing we can offer you is the mosaic design to see up to 16 people at the same time on Google Meet. I leave you the following link for more information: https://gsuiteupdates-es.googleblog.com/2020/04/use-el-diseno-de-mosaico-para-ver-hasta.html
>>>>>>>>>>>>

**Comment by LMJ20** [comment]
Hello.

We are a school in Mexico City and we have the same problem, we cannot enter, the page freezes with the grid view  active with more than 20 participants.   Please we need you help !!

 The only solution for now is to disable grid view but only 16 participants are seen, from with Google Meet.

Thanks

**Comment by iamransom** [comment]
I updated chrome to the last version and it worked

**Comment by GabRioBlu** [comment]
I missed the first half of my graduation because of this. ☹

**Comment by CherylYui** [comment]
Even though I had updated the chrome to the latest version also not worked. Until I removed the grid view extensions or the participants not more than 20 then it's okay.... Please help to fix the problems. Thanks.

**Comment by rmusalMC** [comment]
Some more info.  We did some testing today and found that 16 participants seems to be the number that causes the browser cache.  I wonder if it is related to the 16 limit in native tiled view.

Another finding is that if some people drop off and come back in, we have had success up to 18 people.  We did not test larger numbers.
Hope this helps.

**Comment by jctoy** [comment]
Yep. New install also did not work.

**Comment by vgisbert** [comment]
Reviewing the version history of the extension
https://greasyfork.org/en/scripts/397862-google-meet-grid-view/versions
I have found a way to test previous versions, but until tomorrow I cannot test with more than 20 users.
You have to install the extension (for example for chrome)
https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo
And then go download the corresponding version.
If anyone can prove it by telling us if any historical version works I would appreciate it.

**Comment by rogerl19** [comment]
Fugiman, we have an active Meet session now with 24 participants with the issue.  Do you want to join our Meet and see the issue first hand?

**Comment by rogerl19** [comment]
Using your latest extension, it hangs when there's more than 16 people.  I can provide you with the Meeting link.

**Comment by Fugiman** [comment]
@rogerl19 sure, please email me the link

**Comment by rogerl19** [comment]
https://meet.google.com/oxt-bdvs-dpv

**Comment by Pravin1001** [comment]
> I updated chrome to the last version and it worked

No...I updated chrome and also reinstalled it but it didn't work at all...The screen just crashed

**Comment by Pravin1001** [comment]
> Reviewing the version history of the extension
> https://greasyfork.org/en/scripts/397862-google-meet-grid-view/versions
> I have found a way to test previous versions, but until tomorrow I cannot test with more than 20 users.
> You have to install the extension (for example for chrome)
> https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo
> And then go download the corresponding version.
> If anyone can prove it by telling us if any historical version works I would appreciate it.

If you may test it and it works pls contact me asap

**Comment by Pravin1001** [comment]
> I just found it that it works when i start a meeting but if i do join other meetings it crashes..I think something is happening while joining another meeting..
> I also found this think which helps..If i turn on the tiled view of google meet and then turn on the grid view extension it makes the persons showing in the tiled version  to be viewed in a single column which is awful..
I think if i join the meeting first and then make other participants to join it works[NOT TESTED TILL NOW]
Please comment or reply if this one works
If the solution is found then please contact here or through my mail avrs621kolaapravin@gmail.com

**Comment by Pravin1001** [comment]
Ok guyz...I found this out,the extension worked till 16 persons are in the meeting and when the 17th person enters the meeting boom...The screen freezes and nothing else happens need to close chrome and reopen meet without grid view extension
NEED A SOLUTION ASAP

**Comment by FugiTech** [comment]
On June 14th Google updated Meet with changes to the Tiled view, breaking the Grid View extension. I quickly diagnosed the issue and released a fix as v1.36. However I did not test this fix in a large meeting, which led to browsers hanging or crashing for many users in meetings over 16 people. This was caused by the google code assuming a maximum of 16 videos and entering an infinite loop. I'm extremely sorry I did not test this change thoroughly enough to discover this issue before releasing v1.36.

As of now I am releasing v1.37 which properly fixes the issue. I would like to thank @rogerl19 and his coworkers for hosting a meeting in which I could test this change. In addition to fixing the crash and restoring the expected functionality, it also will automatically lower video quality in large meetings to try and avoid the freezing some users have reported. If the automatic quality is not to your liking, you can override it in the Advanced Settings.

Please note that versions must be reviewed by Google and I do not control how long it takes. **Until the review is complete you can fix the issue by setting your meet layout to Sidebar.** Thanks to @ivanmalgra for finding this fix.

Once again I apologize for the issues caused by my extension, and will endeavor to do better in the future. If you have issues with v1.37 please comment in #225

**Comment by Pravin1001** [comment]
> On June 14th Google updated Meet with changes to the Tiled view, breaking the Grid View extension. I quickly diagnosed the issue and released a fix as v1.36. However I did not test this fix in a large meeting, which led to browsers hanging or crashing for many users in meetings over 16 people. This was caused by the google code assuming a maximum of 16 videos and entering an infinite loop. I'm extremely sorry I did not test this change thoroughly enough to discover this issue before releasing v1.36.
> 
> As of now I am releasing v1.37 which properly fixes the issue. I would like to thank @rogerl19 and his coworkers for hosting a meeting in which I could test this change. In addition to fixing the crash and restoring the expected functionality, it also will automatically lower video quality in large meetings to try and avoid the freezing some users have reported. If the automatic quality is not to your liking, you can override it in the Advanced Settings.
> 
> Please note that versions must be reviewed by Google and I do not control how long it takes. **Until the review is complete you can fix the issue by setting your meet layout to Sidebar.** Thanks to @ivanmalgra for finding this fix.
> 
> Once again I apologize for the issues caused by my extension, and will endeavor to do better in the future. If you have issues with v1.37 please comment in #225

Ahh...Very much thanks...I am very sincere to you...I am awaiting for the 1.37 version and i hope i am back with my students
once again thanks

**Comment by Pravin1001** [comment]
VERY MUCH THANKS RECEIVED THE VERSION 1.37.....IT WORKS VERY THANKS

**Comment by vgisbert** [comment]
Sorry to point out that with 33 users v1.37 hangs. At first he started showing the whole group well, on a second occasion he showed the group in a single column and without movement in the images, and on the third he showed the screen in black.
We are looking forward to a stable version. Many thanks for your work.

**Comment by Mennukido** [comment]
> On June 14th Google updated Meet with changes to the Tiled view, breaking the Grid View extension. I quickly diagnosed the issue and released a fix as v1.36. However I did not test this fix in a large meeting, which led to browsers hanging or crashing for many users in meetings over 16 people. This was caused by the google code assuming a maximum of 16 videos and entering an infinite loop. I'm extremely sorry I did not test this change thoroughly enough to discover this issue before releasing v1.36.
> 
> As of now I am releasing v1.37 which properly fixes the issue. I would like to thank @rogerl19 and his coworkers for hosting a meeting in which I could test this change. In addition to fixing the crash and restoring the expected functionality, it also will automatically lower video quality in large meetings to try and avoid the freezing some users have reported. If the automatic quality is not to your liking, you can override it in the Advanced Settings.
> 
> Please note that versions must be reviewed by Google and I do not control how long it takes. **Until the review is complete you can fix the issue by setting your meet layout to Sidebar.** Thanks to @ivanmalgra for finding this fix.
> 
> Once again I apologize for the issues caused by my extension, and will endeavor to do better in the future. If you have issues with v1.37 please comment in #225

You're the man 😄 Thank you for being so quick about resolving problem. Best regards.

**Comment by Pravin1001** [comment]
> Sorry to point out that with 33 users v1.37 hangs. At first he started showing the whole group well, on a second occasion he showed the group in a single column and without movement in the images, and on the third he showed the screen in black.
> We are looking forward to a stable version. Many thanks for your work.

I am now attending a class with 36 students and it works...I think need a reinstall to work properly

**Comment by vgisbert** [comment]
> 
> 
> > Sorry to point out that with 33 users v1.37 hangs. At first he started showing the whole group well, on a second occasion he showed the group in a single column and without movement in the images, and on the third he showed the screen in black.
> > We are looking forward to a stable version. Many thanks for your work.
> 
> I am now attending a class with 36 students and it works...I think need a reinstall to work properly

I have done this on several occasions.
I've also tried it with the Tampermonkey extension from the Greasy Fork font, with the same results.
I have not tried to clear all the cache and settings of Google Chrome to see if it is fixed, but at the moment it still does not work well.

**Comment by Pravin1001** [comment]
> > > Sorry to point out that with 33 users v1.37 hangs. At first he started showing the whole group well, on a second occasion he showed the group in a single column and without movement in the images, and on the third he showed the screen in black.
> > > We are looking forward to a stable version. Many thanks for your work.
> > 
> > 
> > I am now attending a class with 36 students and it works...I think need a reinstall to work properly
> 
> I have done this on several occasions.
> I've also tried it with the Tampermonkey extension from the Greasy Fork font, with the same results.
> I have not tried to clear all the cache and settings of Google Chrome to see if it is fixed, but at the moment it still does not work well.

Yes It didnt work for me either again...The first class worked and then again it started the old problem

**Comment by vgisbert** [comment]
https://github.com/Fugiman/google-meet-grid-view/issues/225#issuecomment-645330131

**Comment by martaele66** [comment]
Hola!!! Ayuda por fis!! Tengo el mismo problema!!! No puedo ver a todos mis estudiantes. Tengo la cuenta GSUITE, y funcionó bien hasta hace aprox una semana. Ahora no podemos ver más de 16 al mismo tiempo. Soy fanática de MEET por la seguridad que me brinda. Pero deberé pasar a ZOOM si esto no se corrige. Los niños necesitan verse todos. Sería de gran ayuda si lo podemos solucionar. Habla una docente desesperada
