### ISSUE TITLE
Breaks new meet functionality

### ISSUE THREAD

**Issue by lerklompen** [Fugiman/google-meet-grid-view#22]
On G-Suite education domains google has implemented new features:
No other participants can silence or kick out the "owner"/"creator" of the meet
This new functionality is broken when "grid view" is active/installed.

Regards
Mattias Bystedt

**Comment by lerklompen** [comment]
Now it seems to work again!

We will perform some more testing tomorrow to determine if this still is an issue. I will report here. Google has implemented some other new features to Meet in our domain, I don't know if this has temporarily broken stuff...

Regards
Mattias

**Comment by Fugiman** [comment]
I'm sorry it broke. Unfortunately I don't have access to a g-suite education domain and can't test against the changes they are making there, but if you encounter an issue and have an idea what the issue is I can try to address it.

**Comment by lerklompen** [comment]
We might have pinpointed this issue to those users who have the Edu **Enterprice** licenses. I will report back when we have performed some more tests to confirm this. But it seems that something happened explicitly to those users.

The issue no longer seem related to "grid view" at all... 
If so I will close this!
