### ISSUE TITLE
Yesterday's update broke everything

### ISSUE THREAD

**Issue by jctoy** [Fugiman/google-meet-grid-view#220]
**Describe what is broken**
Automatic update doesn't work, consistently crashes Meet (page becomes unresponsive). Problem occurred on two computers.

**Expected behavior**
Expected normal grid behavior as in past version. Also could the updates not be automatic? It would be nice to at least have some warning before I can't attend important meetings.

**Software used:**
 - OS [e.g. Windows 10]: MacOS Catalina, MacOS Mojave
 - Browser [e.g. Chrome, Firefox]: Chrome (both computers)
 - Version [e.g. 22]: 83 with Catalina, other version unknown
 - Extension [e.g. Official Chrome Extension, Tampermonkey]: Google Meet Grid View
 - Grid View Version [e.g. 1.19, 1.23]: 1.36

**Comment by Fugiman** [comment]
Automatic updates are part of the chrome web store and are out of my control. I apologize for the crashes, it has worked fine locally and I did not anticipate them.

Further updates on fixing v1.36 will be in #214
