### ISSUE TITLE
Last update make Google Meet to freeze

### ISSUE THREAD

**Issue by S45bird** [Fugiman/google-meet-grid-view#221]
_Before opening an issue, please check the existing open issues to see if somebody has already reported it! If something is horribly wrong, like all videos showing up in a single column, chances are somebody already reported it. Please reply in that issue instead._

**Describe what is broken**
A clear and concise description of what isn't working.

**Expected behavior**

**Screenshots**

**Software used:**
 - OS [e.g. Windows 10]:
 - Browser [e.g. Chrome, Firefox]:
 - Version [e.g. 22]:
 - Extension [e.g. Official Chrome Extension, Tampermonkey]:
 - Grid View Version [e.g. 1.19, 1.23]:

**Additional context**

**Comment by kitizz** [comment]
I'm seeing this for both firefox and chrome

**Comment by Fugiman** [comment]
Updates will be in #214
