### ISSUE TITLE
A versão 1.36 da extensão google meet grid view não está funcionando,está travando

### ISSUE THREAD

**Issue by Itaca1990** [Fugiman/google-meet-grid-view#222]
_Before opening an issue, please check the existing open issues to see if somebody has already reported it! If something is horribly wrong, like all videos showing up in a single column, chances are somebody already reported it. Please reply in that issue instead._

**Describe what is broken**
A clear and concise description of what isn't working.

**Expected behavior**

**Screenshots**

**Software used:**
 - OS [e.g. Windows 10]:
 - Browser [e.g. Chrome, Firefox]:
 - Version [e.g. 22]:
 - Extension [e.g. Official Chrome Extension, Tampermonkey]:
 - Grid View Version [e.g. 1.19, 1.23]:

**Additional context**

**Comment by Itaca1990** [comment]
Não consigo visualizar todos participantes ,apenas 16.
Estou usando navegador google chrome Versão 83.0.4103.106 (Versão oficial) 64 bits
Windows 10 versão 2004 compilação 19041329
Google meet grid view versão 1.36.0
Navegador chegou até travar quando entra na reunião ,depois funciona removendo a extensão.

**Comment by Fugiman** [comment]
Updates will be in #214
