### ISSUE TITLE
Patreon or PayPal ???

### ISSUE THREAD

**Issue by iamransom** [Fugiman/google-meet-grid-view#227]
Hey! you are a hero this days. That plugin you put together is being used in thousands of schools arround the world. This couple of days fixing that bug should´ve been a mess.  
I couldn´t find any way of making a donation in thank of your hard work. I would realy love to give you a small donation and i´m sure a lot of people would too. 
Have you thought of creating a patreon account or just share a paypal account so we can pitch in with some "thank you donations"

**Comment by Diegovano** [comment]
Hello, if you click Sponsor (just to the left of Watch), you will find a link to his PayPal

![image](https://user-images.githubusercontent.com/36131808/84957546-4fc3e080-b0f3-11ea-908c-1560c729436d.png)

https://www.paypal.me/fugiman
