### ISSUE TITLE
Potential out of memory error in grid.user.js

### ISSUE THREAD

**Issue by al-caughey** [Fugiman/google-meet-grid-view#235]
I'm running v1.37.0 in Chrome (Version 83.0.4103.106 (Official Build) (64-bit)) with Windows 10

I'd just started my Meet and was chatting with the first kid to arrive... I think others were beginning to join when suddenly the UI became unresponsive.  I happened to have the debugger running and the Chrome page reported that the page was paused due to an error in the debugger

In the debugger, it said there was a potential out of memory error in 1164 of grid.users.js

At the end of the Meet (as the students were leaving so the grid was being updated) the Chrome tab became unresponsive again and eventually I got an `oh snap...` out of memory error (but this time did not have the debugger running so not sure if it is the same error)

Hope this helps.  Unfortunately it was my last Meet of the year so I don't know how much more help I can  give you with this

**Comment by pablogirado** [comment]
Me sumo al hilo

Running v1.37.0
Chrome Versión 83.0.4103.106 (Build oficial) (64 bits) (W10)

Si recurren al workarround a mi no me funcionó con la vista de "Sidebar" sino con la vista de "Spotlight"

Gracias.

![WhatsApp Image 2020-06-22 at 20 24 51](https://user-images.githubusercontent.com/65799214/85409760-9757cb80-b53c-11ea-91f9-f5d8f7992541.jpeg)

**Comment by annedroiid** [comment]
@al-caughey This is a duplicate of #255, please close this issue and follow along on the original.

**Comment by al-caughey** [comment]
As per request above, marking as closed/duplicate (of 255... which I presume is supposed to be 225)
Duplicate of #225
