### ISSUE TITLE
Google meet is hanged due to Grid View

### ISSUE THREAD

**Issue by ReubsSchool** [Fugiman/google-meet-grid-view#236]
Grid View is disturbing my sessions and google meet screen stops working with grid view.
Our Institution relies on Grid View for maintaining class discipline.

**Software used:**
 -  Windows 10
 - Browser- Chrome
 - Version -83
 - Extension - Official Chrome Extension
 - Grid View Version-1.37

My Google meet is getting hanged due to grid view extension. It was working fine till last week but all of a sudden its creating problems in my sessions and when i removed the extension it started working as usual. But Grid view is something we rely on for maintaining discipline during online sessions.

**Comment by annedroiid** [comment]
@ReubsSchool This is a duplicate of #225, please close this issue and follow along there.

**Comment by ReubsSchool** [comment]
I have stopped using Grid View Extension because My Google meet hangs when I use it 
Is there any solution to my problem?

**Comment by annedroiid** [comment]
@ReubsSchool As I mentioned, any and all updates will be going in the original issue #225. You can find the latest status there.

I'm not a developer for this extension, just someone trying to help the author by trying to get all of these duplicates issues closed. Messages like that spam the author and don't help at all, as does creating a duplicate issue.

**Comment by ReubsSchool** [comment]
OK..Thanks
