### ISSUE TITLE
GRID IS NOT WORKING 

### ISSUE THREAD

**Issue by shabbirdudhiya** [Fugiman/google-meet-grid-view#260]
Grid view in not as expected
my grid view is not working as expected ....it is showing all participants in a list form.....it is not titled......help me to solve the issue........i tried 3 times reinstalling the extension.......

**Comment by 127001** [comment]
Duplicate of https://github.com/Fugiman/google-meet-grid-view/issues/241

**Comment by YpePoortinga** [comment]
Same here
