### ISSUE TITLE
"include yourself in the grid" stopped working a few weeks ago

### ISSUE THREAD

**Issue by salkerman** [Fugiman/google-meet-grid-view#283]
**Describe what is broken**
"include yourself in the grid" option is broken.

**Expected behavior**
We've been using this option daily and successfully with toddlers while connecting to school from home and ever since it stopped working they don't feel engaged anymore. For them it's like they're not participating anymore. We'd like to see ourselves in the grid again soon.

**Screenshots**
No need of screenshots. I asure all available options are enabled.

**Software used:**
 - OS: macOS Mojave version 10.14.5
 - Browser: Chrome
 - Version: 83.0.4103.116
 - Extension: Google Meet Grid View
 - Grid View Version: 1.37.0

**Additional context**
Can't think of anything else.

**Comment by Eagle-Man** [comment]
> We've been using this option daily and successfully with toddlers while connecting to school from home and ever since it stopped working they don't feel engaged anymore. For them it's like they're not participating anymore. We'd like to see ourselves in the grid again soon.

@salkerman I'm sorry I can't help you, but I wanted to say that that is the first time I have heard this about kids relating to their online schooling.  As a teacher, I find that helpful and fascinating.  Thank you for sharing.

**Comment by yuletide** [comment]
Confirmed happening for me as well

**Comment by digeratimt** [comment]
+1

**Comment by salkerman** [comment]
Just wanted you to know that we migrated to Google Meet Grid View (fix) extension. It works.
