### ISSUE TITLE
Grid view is a bit broken, please fix...

### ISSUE THREAD

**Issue by 0xPolybit** [Fugiman/google-meet-grid-view#285]
First of all, I want to convey that I use **Opera GX** as my go-to browser, and so for using it I also had to install the "Add Chrome Extensions" extensions. So if the extension isn't working for Opera, maybe it because its a Chrome-based extension, and I would then instead request a feature to make it compatible with Opera browsers as well.

Now, the problem is that the [Grid View for Meet](https://chrome.google.com/webstore/detail/google-meet-grid-view/kklailfgofogmmdlhgmjgenehkjoioip?hl=en) is broken. It doesn't work well and instead of the obvious "Grid" format, the names and videos of the participants are on top of one another. This isn't what anyone would wanna see while in a meeting.

But that's only with my friends. For me, it only shows my video as the whole page, and staring at only your face throughout the meeting, is . . . . . . . yea. So I would rather request to fix this and come back as soon as possible.

**Thank You very much for viewing this.**

**Comment by henrik242** [comment]
https://github.com/Fugiman/google-meet-grid-view/issues/292#issuecomment-671675376
