### ISSUE TITLE
Tweaks to your code to record `attendance`

### ISSUE THREAD

**Issue by al-caughey** [Fugiman/google-meet-grid-view#32]
Chris - I'm a High School math and computer teacher in Ottawa Canada.  Like many other schools/school boards, we're starting to use Google Meet for online classes and stumbled across your excellent script.

Based upon feedback from a couple of teachers at our school, I've modified your script so that it will provide a list of students who did not join and did not join the call.

Summary of the changes
 - added a textarea into which you can enter the list of expected attendees... 
     unfortunately, the list of names must be typed or pasted into the field
 - as the code updates the grid layout, the names of the `attendees` are compared with the `invitees` and the textarea is updated to reflect that the person joined.
- if an uninvited person appears in the grid, they are added to the list of attendees but flagged as not invited.

As long as the student appears in the call (ever so briefly), they will be marked as having joined.  I do not record time of entry or exit (and at this point have no plans to add that).

I thought I'd check in with you before presumptuously adding it to the mix here.  Thoughts?

**Comment by Fugiman** [comment]
That's really cool! I'm glad the script has been helpful for you and your school and that you were able to adapt it to your needs!

However, I'm trying to ensure this script stays focused on the core issue of cosmetic changes only. While it'd be convenient for users to have everything in one script it'd quickly become hard to maintain and test each update. Therefore I'd unfortunately have to reject a pull request to add that feature.

**Comment by C4illin** [comment]
@al-caughey This sounds like something that could come in handy at my school as well. Do you have the source code for your modifications published anywhere?

**Comment by AlCaughey** [comment]
At this point no. I will post it as a userscript first... Are you able to add the tampermonkey /greasemonkeey extension to your browser? 

I will look into forking it to a related extension shortly (but may have to jump through some hoops at my end (new territory for all of us!)

**Comment by Fugiman** [comment]
Feel free to continue the discussion but as this is not going to be implemented I'm closing the issue :)

**Comment by C4illin** [comment]
@AlCaughey Yes a userscript would be highly appreciated, it doesn't have to work perfectly. I mostly wanted to see if I could adopt your solution into something that would come in handy for us as well. Just hit me up when you got something working!

**Comment by al-caughey** [comment]
@C4illin - see https://openuserjs.org/scripts/Al_Caughey/Google_Meet_Grid_View_Attendance
It's still rough but it was working reasonably well during experiments with a number of my students this AM.  We should probably continue this discussion elsewhere.

**Comment by C4illin** [comment]
Thanks for the script! It works for me too.

**Comment by al-caughey** [comment]
>  Thanks for the script! It works for me too.
Good to hear!  Please post comments/feedback at https://openuserjs.org/scripts/Al_Caughey/Google_Meet_Grid_View_Attendance 
Thx!
