### ISSUE TITLE
State of `Include yourself...` checkbox gets reversed occasionally

### ISSUE THREAD

**Issue by al-caughey** [Fugiman/google-meet-grid-view#34]
I've only noticed this a couple of times...

In a nutshell, when the `Include yourself...` checkbox was cleared, the video of me appeared in the grid and when I clicked the checkbox again (so that it was now selected), I disappeared... i.e., the opposite of the expected behaviour.  The problem went away after I reloaded the page (perhaps with a <ctrl>+F5).  But I did see it at least once more.

When I have more time, I will try to figure out the steps to replicate.

**Comment by Fugiman** [comment]
I haven't been able to replicate this, and reviewing the code doesn't show anything obviously wrong. If you're able to find out replication steps please let me know!

**Comment by MarcAnt01** [comment]
I can reproduce that, but unable to find repro steps

**Comment by Fugiman** [comment]
My current suspicion is that the grid layout doesn't immediately update when you change a setting, it only updates when Google Meet decides to redo the layout. It's theoretically possible that you could enable the setting and nothing happens, then as you disable it Meet applies the layout just before, making it seem inversed? Next time it happens try moving your mouse in & out of the window or clicking in blank space to see if it fixes itself, and let me know the result :)

**Comment by Fugiman** [comment]
This should be fixed in v1.27
