### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by rhnonose** [Fugiman/google-meet-grid-view#37]
There's no license in place for this and many institutions would benefit from having an open source license to use this.

**Comment by Fugiman** [comment]
I don't understand why a license is required to install the script, and am not interested in giving others redistribution or modification rights.

**Comment by al-caughey** [comment]
Chris - are you aware that the license for the Google Meet Grid View extension (which wraps your script) states that modification, distribution and commercial use **are** permitted... (https://github.com/stgeorgesepiscopal/google-meet-grid-view-extension/blob/master/LICENSE).  This seem counter to your comments above.  Does this need to be clarified?

**Comment by Fugiman** [comment]
My understanding is that the LICENSE for that repo applies only to the code in that repo and not its dependencies, which seems fairly normal.

**Comment by BlackVegetable** [comment]
Then that other extension is in violation of copyright law as it is redistributing your source code via submodule, no?

Is there a license you *would* be comfortable associating with? I would like to use your code but am unwilling to violate copyright law to do so.
