### ISSUE TITLE
Add speaker highlight delay

### ISSUE THREAD

**Issue by morganbye** [Fugiman/google-meet-grid-view#39]
A delay could be added to `VolumeDetectionProxyHandler` so as to smooth speaker highlighting.

Currently, on breathing or pauses in conversation the speaker selection rapidly selects and deselects. This is a problem when speaking with nationalities with a slow speaking speed and can yield a distracting disco-like experience.

**Comment by Fugiman** [comment]
There's already a half-second delay; you have to stop talking for half a second for it to stop highlighting you. Are you not finding this long enough? How long would you like it to be?

**Comment by morganbye** [comment]
Just tried it in the team stand-up. Looks like the delay isn't being implemented at all, as evidenced when someone with a mechanical keyboard started typing and we saw a strobe effect.

Browsers
- Chrome: Version 80.0.3987.163 (64-bit)
- Brave: Version 1.5.122  based on Chromium: 80.0.3987.162 (64-bit)

**Comment by Fugiman** [comment]
I think I found a potential bug around this that was fixed in v1.18. Please let me know if it's still not working for you!

**Comment by morganbye** [comment]
This morning's call is much better. I now see an ~0.5s fade on the highlight when a speaker stops speaking which also massively helps reduce the strobing effect.

Much appreciated.
