### ISSUE TITLE
Stopped working some time mid-day 2020-04-08

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [Fugiman/google-meet-grid-view#40]
Some time today (2020-04-08, US Eastern time), the extension version of this userscript stopped working.

Reposting from https://github.com/stgeorgesepiscopal/google-meet-grid-view-extension/issues/13 where I was suggested to post here, since that extension just wraps a copy of this user script via a git submodule

----

I think something must have changed on the google meet site, as this extension was working earlier today, but now it's not working at all -- it doesn't add its button to the meet UI, and clicking the grid toggle in the extension itself doesn't do anything any more.

There's an error in my dev console that I think is coming from this extension:
```
Error in event handler: TypeError: Cannot read property 'click' of undefined
    at chrome-extension://bjkegbgpfgpikgkfidhcihhiflbjgfic/js/inject.js:41:64
```

Which corresponds to ... code I can't find in this repo?
```
// ...
injectScript(chrome.runtime.getURL('js/google-meet-grid-view/grid.user.js'));

//injectScript(chrome.runtime.getURL('js/messaging.js'));
chrome.runtime.onMessage.addListener(
    function(request, sender, sendResponse) {
        
        let gridOn = !!document.getElementsByClassName('__gmgv-vid-container').length
        let showOnlyVideo = JSON.parse(localStorage.getItem('gmgv-show-only-video'))
        let highlightSpeaker = JSON.parse(localStorage.getItem('gmgv-highlight-speaker'))
        let includeOwnVideo = JSON.parse(localStorage.getItem('gmgv-include-own-video'))
        console.log(localStorage)

        if(request.hasOwnProperty('startup')){
            console.log('init')
        } else if(request.hasOwnProperty('toggleGrid')){
            document.getElementsByClassName('__gmgv-button')[0].click()
            // ^^^ this line ^^^
// ...
```

I have version `2020.4.7` installed currently.

----

`2020.4.7` of that extension I believe maps to commit bef6bff here. That's not the latest, but the commit log from that to current HEAD of `master` doesn't look like it has any functional changes, only translation changes.

**Comment by OceanFoxy** [comment]
Can confirm this situation. It seems like whatever is causing the issue might be in the process of rolling out (from Google)? It's not working for about 9/10 people in all my classes today including teachers reporting it not working. But to be specific: there are still 1-2 people that have it working per class.

**Comment by mgabeler-lee-6rs** [comment]
On more digging, this was an error with the extension and not the user script itself. Closing.

**Comment by sreyemnayr** [comment]
This was on me, Chris. Sorry!
