### ISSUE TITLE
"Only Show Participants with Video" Not Updating Properly

### ISSUE THREAD

**Issue by rogerl19** [Fugiman/google-meet-grid-view#41]
Noticed when "Only Show Participants with Video" is checked, and new person joins the Meet or person turns on their camera, the person doesn't show up on the grid unless I move my mouse.  When user leaves the meeting or turns off their camera, they are removed from the grid correctly.

In my testing, I went into the same Meet as the same person on 5 different devices.  Maybe that could trigger the issue. 

When "Only Show Participants with Video" is not checked, then everything works correctly.  New person joins the Meet, they automatically get added to the grid.

**Comment by Fugiman** [comment]
This should be fixed in 1.27
