### ISSUE TITLE
Grid View is not running on this page

### ISSUE THREAD

**Issue by tamingil** [Fugiman/google-meet-grid-view#42]
1.17.0 Grid view is not running on this page. Reloaded, uninstalled and installed, any ideas?

**Comment by tamingil** [comment]
Sorry this is for a "forked" version. i.e. I downloaded it and packed it to my developer console for internal use in our domain. I just zipped the "chrome" folder and packed it. Dev tools complains about not seeing grid.user.js which seems to be outside this folder... Should I just move that inside the "chrome" folder before packing?

**Comment by sreyemnayr** [comment]
Run  `./build.sh` and you should have your zipped extension
