### ISSUE TITLE
Microsoft Edge extension

### ISSUE THREAD

**Issue by MarcAnt01** [Fugiman/google-meet-grid-view#48]
Hi, I have seen you've released officially a Chrome extension. It works properly on Microsoft Edge (Chromium version), what about releasing it also in the Microsoft Edge Store?
https://www.microsoft.com/en-us/store/collections/edgeextensions/pc

**Comment by Fugiman** [comment]
Sure, it's in review right now.

**Comment by Fugiman** [comment]
Now available: https://microsoftedge.microsoft.com/addons/detail/ogbbehbkcmdciebilbkpjgopohnpfolj

**Comment by MarcAnt01** [comment]
Thank you

**Comment by MarcAnt01** [comment]
@Fugiman are there any problems with Edge extension submission? I am still on v.30 usually it used to get updates faster than the version in Chrome Web Store

**Comment by Gass-by-Revi** [comment]
@MarcAnt01 Últimamente ha habido algunos problemas con la extensión de Chrome, tal vez @Fugiman tarde un tiempo en mandarlo. Pero no lo sé, eso dependerá de como le vaya a el. Sé que para Chrome ya está la v1.32

**Comment by MarcAnt01** [comment]
> @MarcAnt01 Últimamente ha habido algunos problemas con la extensión de Chrome, tal vez @Fugiman tarde un tiempo en mandarlo. Pero no lo sé, eso dependerá de como le vaya a el. Sé que para Chrome ya está la v1.32

I don't understand your language, try to use English

**Comment by Gass-by-Revi** [comment]
Ok, sorry. I don't speak well English. I wish you understand me.

We have had some problems with the Chrome extension, maybe @Fugiman  will take a while to send it. But I don't know, that will depend on how he does. I know that Chrome is already the version v1.32

**Comment by Gass-by-Revi** [comment]
> OK lo siento. No hablo bien ingles Deseo que me entiendas
> 
> Hemos tenido algunos problemas con la extensión de Chrome, tal vez @Fugiman tarde un poco en enviarla. Pero no sé, eso dependerá de cómo lo haga. Sé que para Chrome ya es la versión v1.32

If you don't understand that, tell me please.

**Comment by MarcAnt01** [comment]
> > OK lo siento. No hablo bien ingles Deseo que me entiendas
> > Hemos tenido algunos problemas con la extensión de Chrome, tal vez @Fugiman tarde un poco en enviarla. Pero no sé, eso dependerá de cómo lo haga. Sé que para Chrome ya es la versión v1.32
> 
> If you don't understand that, tell me please.

Yes, I have understood, but Chris said yesterday that there were some problems with the submissions for Edge store

**Comment by Gass-by-Revi** [comment]
> > > OK lo siento. No hablo bien ingles Deseo que me entiendas Hemos 
> > > tenido algunos problemas con la extensión de Chrome, tal vez @Fugiman tarde un poco en enviarla. Pero no sé, eso depende de cómo lo haga. Sé que para Chrome ya es la versión v1.32
> > 
> > 
> > Si no entiendes eso, dime por favor.
> 
> Sí, lo he entendido, pero Chris dijo ayer que hubo algunos problemas con las presentaciones para la tienda 

> > > OK lo siento. No hablo bien ingles Deseo que me entiendas Hemos 
> > > tenido algunos problemas con la extensión de Chrome, tal vez @Fugiman tarde un poco en enviarla. Pero no sé, eso depende de cómo lo haga. Sé que para Chrome ya es la versión v1.32
> > 
> > 
> > Si no entiendes eso, dime por favor.
> 
> Sí, lo he entendido, pero Chris dijo ayer que hubo algunos problemas con las presentaciones para la tienda Edge

I don't know that, may be it comes from the same problem. But I don't know more, sorry.

**Comment by Fugiman** [comment]
I submit updates to all extension stores at the same time. Firefox tends to update within 20 minutes, Edge tends to take several days. Chrome used to take a week and now seems to take ~4 hours, I'm assuming they prioritize based on number of users so reviews got faster once we got 1M users.

There's nothing I can do about the review delay.

**Comment by Gass-by-Revi** [comment]
@Fugiman I I would like to know, if you could teach me a bit about the programming issues you handle and how to manage this website

**Comment by Gass-by-Revi** [comment]
I don't know if you understand me

> @Fugiman Me gustaría saber, si pudiera enseñarme un poco sobre los temas de programación que maneja y cómo administrar este sitio web

**Comment by Fugiman** [comment]
I'm sorry, I do not have time to be your mentor

**Comment by Gass-by-Revi** [comment]
ah, ok, doesn't matter
