### ISSUE TITLE
Grid view only displaying 6 people

### ISSUE THREAD

**Issue by mathwhi10** [Fugiman/google-meet-grid-view#53]
My school uses google meet for video conferencing with each of our classes and as a team. We have been using grid view to helpaid in watching the students while teaching . This morning, none of us could get it to show more than 6 people at a time.

**Comment by adr29truck** [comment]
See #54

**Comment by Fugiman** [comment]
Closing as this was fixed in v1.18, despite the official chrome extension not working until Google accepts the new version.
