### ISSUE TITLE
Chrome Web Store Delay

### ISSUE THREAD

**Issue by jyergatian** [Fugiman/google-meet-grid-view#58]
The Chrome Web Store is still listing version 1.15.0 - even after an Empty Cache and Hard Reload.  Is there a typical waiting period for new updates to become available?

Chrome Web Store link: [https://chrome.google.com/webstore/detail/google-meet-grid-view/kklailfgofogmmdlhgmjgenehkjoioip](https://chrome.google.com/webstore/detail/google-meet-grid-view/kklailfgofogmmdlhgmjgenehkjoioip)

![chrome_google_com_webstore_detail_google-meet-grid-view_kklailfgofogmmdlhgmjgenehkjoioip](https://user-images.githubusercontent.com/1728967/79367908-74d58080-7f03-11ea-9e82-0b72180b60f2.png)

**Comment by adr29truck** [comment]
My assumption is that it can take some time for Google to push the update to all regions. But to install the latest version you can always manually install it as instructed in #54

**Comment by Fugiman** [comment]
Google has to review every update to the extension. In my experience this takes ~5 days, and it may be rejected.
