### ISSUE TITLE
grid view not showing all participants

### ISSUE THREAD

**Issue by iteachk5** [Fugiman/google-meet-grid-view#59]
A few days ago all 20 participants showed up in the grid, but now only 5 are showing....We really want it back so that all participants will show up in our Google Meets.  Help!!!????

**Comment by jyergatian** [comment]
Hey @iteachk5 , this issue has been identified and fixed. More info in #53

**Comment by Fugiman** [comment]
Closing as this was fixed in v1.18, despite the official chrome extension not working until Google accepts the new version.
