### ISSUE TITLE
Google Grid Help

### ISSUE THREAD

**Issue by Mallorylynch** [Fugiman/google-meet-grid-view#60]
Google grid is messed up. When I am conferencing with 22 students, it only shows 5 screens at a time. It was showing all of my screens Monday April 13.

**Comment by jyergatian** [comment]
Hey @Mallorylynch, this issue has been identified and fixed.  More info in #53

**Comment by Mallorylynch** [comment]
This still isnt working.

**Comment by Fugiman** [comment]
Closing as this was fixed in v1.18, despite the official chrome extension not working until Google accepts the new version.
