### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by amacneil** [Fugiman/google-meet-grid-view#63]
Under what conditions may we use this script? For example, can we include it in a private chrome extension used internally within a company?

You stated [elsewhere](https://greasyfork.org/en/forum/discussion/74294/x) that it is "open source", which the OSI [defines](https://opensource.org/osd) as requiring "Free Redistribution". However, you also stated that you do not want to us a license which allows for redistribution (which clearly runs counter to it being open source).

If you don't want _redistribution_ that's fine, but what about _distribution_? This whole thing will be a lot easier if you can add a license file explaining how you wish to allow people to use this code, even if it's just one or two sentences you write yourself (although any existing/standard license would be preferred).

**Comment by vtnate** [comment]
Great question, issue. For the creators, the [mit license](https://en.wikipedia.org/wiki/MIT_License) is common for open source software.

**Comment by Fugiman** [comment]
The lack of a license is not a mistake. You are correct that this means it is not actually "Open Source", I should have said "the source code is public" instead. Unfortunately there is no existing license that I could find that meets my need.

All open source libraries allow for the right to modify & redistribute the code, which is not what I'm looking for. My intent with this repo is to allow personal use (preferably from the official releases) of the code and to allow issues and PRs to the code. I do _not_ intend to allow others to distribute it to any other individual, instead they should direct them to install it from an official release of the code.

Privately distributing is a gray area. I can't stop you from doing so, but I would greatly prefer if you used an official release or reached out to me via email to discuss your use case. Depending on your use case I could offer a separate license to your company for internal use.

As someone who has created, maintained and used other open source projects I get that this is relatively draconian. However multiple extensions have already taken my code and used it to solicit donations or market their company, and it's extremely hard to fight against them without legal recourse.

**Comment by MarcAnt01** [comment]
@Fugiman I've sent you an e-mail

**Comment by hpleitez** [comment]
@Fugiman I am sending you an email as well.

**Comment by amacneil** [comment]
Thanks @Fugiman, appreciate the clarity. I'm not a lawyer but it might be worth putting your above comment into a license file, so at least people are clear on how you would like the code to be used. Of course how the code is used is your decision to make and we want to respect it.

FYI it also looks like Google is planning to add official grid view support (up to 16 participants) "[later this month](https://www.reuters.com/article/us-alphabet-google-conferencing/googles-fast-growing-meet-video-tool-getting-zoom-like-layout-gmail-link-idUSKCN21Y1XI)".

**Comment by Fugiman** [comment]
Closing as the README has been updated. Thank you for the civil discussion :)

**Comment by MarcAnt01** [comment]
I think it's better to add those info in LICENSE.md otherwise GitHub still complains about missing license
