### ISSUE TITLE
[FEATURE REQUEST] Force 16:9 

### ISSUE THREAD

**Issue by revett** [Fugiman/google-meet-grid-view#66]
Thanks for the great extension 👏

## Feature Request

The new **Force 16:9** in **Screen Capture Mode** from v1.17 makes an overall improvement to the look and feel of a call.

Would it be possible to extract this part out in to a separate toggle in settings?

**Comment by Fugiman** [comment]
The way I force 16:9 actually looks terrible in my opinion (especially on small monitors or windows that aren't 16:9), and I wouldn't want people to be misled in thinking it's a generically useful feature. In v1.18 I adjusted the grid calculation to better avoid black bars which I think should be better than a 16:9 toggle.

If you're able to share screenshots describing what you like about it I can try to think of ways to support that, but I'd like to avoid toggles as much as possible.

**Comment by revett** [comment]
@Fugiman That's understandable 👍

The main thing I think it adds compared to the current grid is the natural look of 16:9 videos, instead of the more 1:1 aspect ratio that the videos go to sometimes due to the grid.
