### ISSUE TITLE
People are not allowed into the google meet room

### ISSUE THREAD

**Issue by Ruurlo** [Fugiman/google-meet-grid-view#69]
Today there was a Google meeting session with a group. Some of the children were not in a google meet session. She clicked on the link and the organizer was not asked to let them in. Even after closing the browser session and doing it again.
What could this be? Everything worked fine with the same group last week

**Comment by Fugiman** [comment]
I'm not aware of anything in this extension that would affect joining meetings or asking to join a meeting. Testing it myself it looks like it works as expected.

**Comment by MarcAnt01** [comment]
> Today there was a Google meeting session with a group. Some of the children were not in a google meet session. She clicked on the link and the organizer was not asked to let them in. Even after closing the browser session and doing it again.
> 
> What could this be? Everything worked fine with the same group last week

That doesn’t depend on the extension, the domain admin has probably blocked people without GSuit account to join video-calls.
