### ISSUE TITLE
Authorized Firefox extension

### ISSUE THREAD

**Issue by vtnate** [Fugiman/google-meet-grid-view#71]
I installed this through the link in the readme to the Firefox addons, and it works great on Firefox 75. However, it also shows a warning under the grid button saying this is not an authorized extension and directs me to the Firefox addon page where I installed it from. Probably needs some connection to Mozilla to tell them this is kosher?

**Comment by Fugiman** [comment]
Thanks for the heads up! Turns out Firefox generates a unique URL for each user's installation of the extension, so while the detection worked for me it wouldn't work for anyone else. I've fixed it in v1.21
