### ISSUE TITLE
The icon of Microsoft Edge extension doesn't look good

### ISSUE THREAD

**Issue by MarcAnt01** [Fugiman/google-meet-grid-view#72]
![image](https://user-images.githubusercontent.com/43090263/79543230-62874e00-808d-11ea-8ad1-b1b02888704e.png)
On the left Microsoft Edge store extension, on the right Chrome web store one.
Microsoft Edge store one has too thin lines.

**Comment by Fugiman** [comment]
Chrome web store will be updated to match the Microsoft edge version when they accept the submission. the "thinner lines" is likely caused by the addition of white lines to make it stand out more in dark mode themes.

**Comment by MarcAnt01** [comment]
> Chrome web store will be updated to match the Microsoft edge version when they accept the submission. the "thinner lines" is likely caused by the addition of white lines to make it stand out more in dark mode themes.

I use a 3000x2000 13.5 inches screen (maybe that's why) and they look too thin to me

**Comment by Fugiman** [comment]
Contrast of the icon should be improved in v1.29
