### ISSUE TITLE
Does not work in Firefox after version 1.20 

### ISSUE THREAD

**Issue by henrik242** [Fugiman/google-meet-grid-view#76]
1.20 is the last version that works for me in Firefox Developer Edition 76.0b3 on macOS Catalina.

The grid icon isn't present anymore.  I'm using the ViolentMonkey extension.

**Comment by henrik242** [comment]
Also, highlight and see myself doesn't work

**Comment by Fugiman** [comment]
>I'm using the ViolentMonkey extension

Thanks for including this, I was able to reproduce the issue and it is fixed in v1.23
