### ISSUE TITLE
When in grid view mode mouse hover prevents the interaction with people in the last line of the grid

### ISSUE THREAD

**Issue by MarcAnt01** [Fugiman/google-meet-grid-view#80]
Options for pinning and disabling audio are unusable

**Comment by Fugiman** [comment]
Can you show a screenshot of this? I'm not sure what exactly you mean.

Do note that you can pin & mute people from the participant list as well (the button next to grid view in the top right)

**Comment by MarcAnt01** [comment]
Here you go
![image](https://user-images.githubusercontent.com/43090263/79633950-ef063f00-8167-11ea-930e-eb4530aa08de.png)

**Comment by Fugiman** [comment]
Fixed in v1.24

**Comment by MarcAnt01** [comment]
Thank you, how have you fixed it? Have you disabled the hover?

**Comment by Fugiman** [comment]
I move the videos up while the bottom bar is displayed. This unfortunately squishes the videos a bit, but ensures everyone is visible and the pin/mute buttons are interactable.

**Comment by MarcAnt01** [comment]
@Fugiman doesn't seem to work when a user is presenting

**Comment by Fugiman** [comment]
In my testing it seems to work fine while presenting? Please make sure you're on v1.24+, the current Chrome Extension is only on v1.23

**Comment by MarcAnt01** [comment]
> In my testing it seems to work fine while presenting? Please make sure you're on v1.24+, the current Chrome Extension is only on v1.23

I use Edge one which seems to get updates faster. I was on 1.24 and it wasn't working with the presentation, I will see if it happens constatly or it was just a race condition👍
