### ISSUE TITLE
Google will add integrate this feature shortly

### ISSUE THREAD

**Issue by aslafy-z** [Fugiman/google-meet-grid-view#81]
See https://www.reuters.com/article/us-alphabet-google-conferencing-idUSKCN21Y1XI

**Comment by MarcAnt01** [comment]
I don't understand the purpose of this ticket

**Comment by sreyemnayr** [comment]
Google’s also only implementing 16 cameras. Chris’ extensions will still offer a lot of helpful functionality.

**Comment by Fugiman** [comment]
I am aware that Google is working on a native version of Grid View and am looking forward to its release. Once it's out I'll be able to evaluate and share future plans, but until then I'm not going to speculate on what may be :)
