### ISSUE TITLE
Add option for sorting by surname

### ISSUE THREAD

**Issue by maxbambi** [Fugiman/google-meet-grid-view#82]
I'm a teacher and i'm using your plugin to see all students during my lessons.
Students screens appears sorted by name, because their account names have been created in the form "First name Surname", but I know mostly by surname and I search them in the screen by surname (and it is no so easy when students are more than 20).
I have created a javascript function
```
  function swapName(n){
    n = n.toUpperCase();
    var pos = n.indexOf(" ");
    if (pos>0){
      var n2 = n.substring(pos+1) + " " + n.substring(0, pos);
      //console.log('[google-meet-grid-view] Name:' + n2);
      return n2
    } else {
      //console.log('[google-meet-grid-view] Name:' + n);
      return n;
    }
  }
```
that changes strings ("Massimo Bambi" becomes "BAMBI MASSIMO")
and I have inserted this function in your sort command
```
ret.sort((a, b) => swapName(a[magicKey].name).localeCompare(swapName(b[magicKey].name)) || a[magicKey].id.localeCompare(b[magicKey].id))
```

This function searches only first space in string, so it is not working with multiple names,
but can you add this as an option?

**Comment by sreyemnayr** [comment]
try lastIndexOf() and you'll get the last space instead of the first.

**Comment by maxbambi** [comment]
> try lastIndexOf() and you'll get the last space instead of the first.
This solution is equivalent to the the other one, in case of a single space, and creates wrong results with surnames composed by two or more words.
In my contest (I'm Italian) there are more surnames with two words, than people with two names.

**Comment by Fugiman** [comment]
It is not possible for me to provide any option that transforms names safely. The name I'm given by Google contains the entire name as one string and it is impossible to determine which part is the given name and which part is the surname, assuming that there even is a given name or surname present. This is especially true given that the extension is used internationally.

Quick examples of what could go wrong:
 - Splitting by space to order by surname doesn't work if no surname is provided (`Chris`)
 - It also doesn't work in languages that don't put spaces between names
 - Splitting by the first space doesn't work if the given name contains multiple words or a middle name is provided (`Chris Fugi Gamble`)
 - Splitting by the last space doesn't work if the surname contains multiple words (`Chris de la Cruz`)
 - Splitting by anything and reversing the order doesn't work if the name is already in `surname given name` order

For more problems dealing with names [Falsehoods Programmers Believe About Names With Examples](https://shinesolutions.com/2018/01/08/falsehoods-programmers-believe-about-names-with-examples/) is a fun read.

Unfortunately I can't comfortably add an option that won't work for everyone. It will be surprising and confusing if the option says "Display participants by `surname, given name`" and it doesn't work consistently, leading to upset users and support requests. I am considering adding an `Advanced Options` page for partially working features like this, but I haven't decided yet and it'd be at least a little while before it's done.

**Comment by sreyemnayr** [comment]
You’re right, that _was_ an interesting read!

**Comment by Fugiman** [comment]
This has been added to the Advanced Settings menu in v1.30
