### ISSUE TITLE
Only 6 participants in the grid 

### ISSUE THREAD

**Issue by G1ZMOE** [Fugiman/google-meet-grid-view#83]
Hi,

I copied the src and modified the .json to suit our college.

But only 6 x participants appear in the grid, and the "include yourself in the grid" does not work.

Any tips?

the only thing I see differently is when I click on your one it says grid view is not running on this page, but on my extension, I don't have this.

Thank you

**Comment by Fugiman** [comment]
Hi. I will not support attempts to illegally copy my extension. Thank you for your understanding.
