### ISSUE TITLE
Chrome refused to load the script

### ISSUE THREAD

**Issue by svenjacobs** [Fugiman/google-meet-grid-view#85]
Script was working fine the last days but suddenly stopped working. It seems it stopped working with the latest Chrome version 81.0.4044.113 (on macOS).

<img width="1012" alt="Screenshot 2020-04-21 at 16 22 09" src="https://user-images.githubusercontent.com/255313/79877970-2c2f3300-83ed-11ea-82a5-8d5348b7eb08.png">

Script version is 1.24 and is installed/managed via Violentmonkey 2.12.7.

**Comment by medlir** [comment]
I was having this issue as well the last couple days, but only in ViolentMonkey, and not TamperMonkey.  I resolved this for myself by adding a directive of:

`// @inject-into  content`

To make ViolentMonkey explicityly inject it into content context rather than page context.

**Comment by cblake777** [comment]
Can confirm, this fix worked for me as well

**Comment by svenjacobs** [comment]
Yes, that line fixes it for me, too. Would be nice to see fix in the project :)

**Comment by Fugiman** [comment]
yeah, i'll add the fix officially once the work-day is over and I've had a chance to verify it works on all browsers & extensions

**Comment by Fugiman** [comment]
Fixed in v1.25
