### ISSUE TITLE
Unauthorized extension warning in Chrome with Violentmonkey

### ISSUE THREAD

**Issue by svenjacobs** [Fugiman/google-meet-grid-view#86]
I get the "unauthorized extension" warning in Chrome with Violentmonkey. It seems the extensions expects the URL `chrome-extension://kklailfgofogmmdlhgmjgenehkjoioip` in case of Chrome however in my case it's `chrome-extension://jinjaccalgkegednnccohejagnlnfdag`.

**Comment by Fugiman** [comment]
Fixed in v1.25
