### ISSUE TITLE
Names appearing in Screen Capture Mode if user turns off camera

### ISSUE THREAD

**Issue by TylerLoch** [Fugiman/google-meet-grid-view#89]
When a user has disabled their camera, their name appears in the grid when Screen Capture Mode is enabled, which works against the privacy intent of the feature.
Unfortunately, I'm new enough to the extension that I cannot tell if this is a regression, or has always been the case.

Here's a screenshot testing and demonstrating the issue:
https://imgur.com/a/VYwQBdp

Thank you!

**Comment by Fugiman** [comment]
This wasn't really intended as a privacy feature, instead it was intended for people who are capturing the meet with another program and mixing it for broadcast to Twitch or YouTube. Please note that Grid View does NOT affect the "record meet" feature in any way.

Regardless names no longer show up at all during Screen Capture Mode in v1.26

**Comment by TylerLoch** [comment]
Thank you!
To give you an idea of this use case, our users enjoy the Screen Capture Mode's ability to take screenshots of student gatherings for social media (or other public) use, where direct sharing of student names is prohibited.
