### ISSUE TITLE
With "Include yourself in Grid" checked but video turned off, I still see myself when "Only show participants with Video" is checked

### ISSUE THREAD

**Issue by enilsen16** [Fugiman/google-meet-grid-view#90]
**Describe what is broken**
With "Include yourself in Grid" checked but video turned off, I still see myself when "Only show participants with Video" is checked.

**Expected behavior**
I'd expect that I wouldn't see myself with both of those options checked.

**Software used:**
 - OS [e.g. Windows 10]: Ubuntu 20.04
 - Browser [e.g. Chrome, Firefox]: Firefox
 - Version [e.g. 22]: 
 - Extension [e.g. Official Chrome Extension, Tampermonkey]: Official Extension
 - Grid View Version [e.g. 1.19, 1.23]: 1.25

**Comment by enilsen16** [comment]
This to only happen sometimes.

**Comment by Fugiman** [comment]
If you are unmuted you'll also show up, the description of the toggle is a bit incorrect. Is that what was happening?

**Comment by enilsen16** [comment]
Yes that's what the issue is. I just confirmed that's the behavior I didn't expect
