### ISSUE TITLE
Add ability to exclude specific users in Screen Capture mode

### ISSUE THREAD

**Issue by paul-lrr** [Fugiman/google-meet-grid-view#92]
**Is your feature request related to a problem? Please describe.**
For screen capture/streaming purposes, I will often have extra "dummy" users in a meeting. eg. A user whose camera is the program output from the streaming software to show other participants in the call what is being sent out, or I will connect with my phone in addition to the computer to facilitate communication during breaks without it being audible to the stream. At the moment, these users are included in the Screen Capture mode grid. Obviously I can just not use the crop of their video output, but including them in the grid shrinks all the "true" participants's videos.

**Describe the solution you'd like**
An option, possibly in the user menu, to exclude users from all grid output. Sort of like pinning user, but the opposite :)

**Describe alternatives you've considered**
Initially I thought this could be mostly resolved with the "Only show participants with video" option, but that is disabled in Screen Capture mode. After thinking about it, I realize that this makes sense to preserve the grid if a user has camera trouble etc. My thought is that this exclude user option would be for users that you know should _never_ be included in the grid.

**Additional context**
Amazing work on this script, btw. I just wish someone would come out with a video chat service that is actually built with streaming in mind and has some of these features built in. I have messed around with hacking obfuscated google code in the past and it is a real pain.

**Comment by Fugiman** [comment]
Added in v1.27

Please note the following caveats:
- Screen Capture mode detects reconnections by the participant's name, if the same user connects multiple times it appends an autoincrementing ID to the name to try to separate them. This means if the same name has multiple connections and more than one disconnects, they may swap places.
- Hiding a participant hides that specific connection _and_ the name+id for screen capture mode, so they will still be hidden if they reconnect.
- In non-screen-capture mode they will not be hidden if they reconnect
- Hiding participants in screen capture mode will cause participants to shift to fill the gap, and potentially increase the grid size

To reset the hidden list please disable & re-enable grid view

**Comment by paul-lrr** [comment]
This will work great! Thanks.
