### ISSUE TITLE
Support for just a couple of windows

### ISSUE THREAD

**Issue by Rossolson** [Fugiman/google-meet-grid-view#95]
While viewing classes in Meet, the Deaf/Hard of Hearing students don't need to see all other members of the classroom, but would greatly benefit from seeing the instructor's video as well as the sign language interpreter's video.

The full class grid view's bandwidth causes streams to be degraded in one of two ways: lowering the resolution and/or lowering the frame rate. These a good trade offs for participants that can still get decent enough audio, but these tradeoffs make signed communication nearly impossible.

I will be looking at the JS to see if there's a way to keep a state for hiding the un-needed streams (or conversely, highlighting/promoting the desired streams) likely through an array of the stream's IDs with a binary flag to hide or show them. Then add an onlick to toggle the states. Then add a 'minimized' icon to represent the closed streams to expand them as needed. 

If anyone would like to work with me on this, please drop me a line.

**Comment by Fugiman** [comment]
First off, if you don't need to see more than a few participants I highly recommend simply not using grid view. Google's native layouts prioritize whoever has spoken last, so if only the instructor and intepreter make noise then they'll be easily visible. Grid View is focused on the specific use case of showing everyone in the call which isn't always what you need.

That said, v1.27 adds support for hiding individual participants and you _can_ use this to remove everyone but the instructor & interpreter. You can hide a participant by clicking the eye icon when hovering over a participant. This will remove them permanently. To restore hidden participants, toggle grid view off & on again.

**Comment by Rossolson** [comment]
1) This assumes that students who sign are making sounds, which isn't the case, and the sign language interpreter is never speaking, so that takes me to...

2) Hiding Participants: I hadn't seen the  hide participant option, but that will help enormously. I should be able to close out the other students which will certainly help. As the class is meant to be interactive, it would be nice to have a way of 'unhiding' a hidden student individually.

Thank you so much for your work here.

**Comment by Fugiman** [comment]
In v1.28 you can unhide a hidden participant in the participant menu. Click the people icon next to the grid view button, click the participant's name to expand the menu, and press the eye button to show or hide the participant.
