### ISSUE TITLE
What is the difference between Grid View and Meet's native tiled view?

### ISSUE THREAD

**Issue by KeenRivals** [Fugiman/google-meet-grid-view#99]
In a meeting, if you hit the dots > layout > tiled, you get a similar layout to grid view. What's the difference between that and google-meet-grid-view?

**Comment by jeff-divert** [comment]
This google-meet-grid-view existed prior to Google introducing tiled view recently.

**Comment by Fugiman** [comment]
The primary difference is that my extension supports meetings over 16 people. I've seen pictures of people using it in meetings over 100 people. It also has a number of secondary benefits that the tiled layout doesn't offer: highlighting the speaker, including yourself in the grid, hiding participants without video, hiding individual participants, and maintaining the grid even when someone is presenting or pinned.

If you find the tiled layout meets your needs I encourage you to use it and uninstall the extension, but I personally find the extra features of Grid View worthwhile and will continue to support it until I feel Google Meet has equivalent functionality.

**Comment by KeenRivals** [comment]
Thanks for that. I didn't know if there was a difference or not.
